/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package capasPresentacion;


import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JLayeredPane;
import javax.swing.JPanel;
import javax.swing.JOptionPane;
import ClasesDAO.UsuarioDAO;
import Clases.Usuario;


/**
 *
 * @author LAS
 */
public class acceso extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(acceso.class.getName());
    private final UsuarioDAO usuarioDAO = new UsuarioDAO();

    /**
     * Creates new form acceso
     */
    public acceso() {
        initComponents();
        setLocationRelativeTo(null);
        setTitle("Minimarket Kathycita");
        setIconImage(new ImageIcon(getClass().getResource("/imagenes/tienda.png")).getImage());
        jLabel5.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 24));
        jLabel1.setFont(new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 14));
        jLabel2.setFont(new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 14));
        jButton1.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 14));
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));






        
        getContentPane().setBackground(new java.awt.Color(200, 230, 255));
       
     // Escalar el logo al tamaño del JLabel
        javax.swing.ImageIcon iconoOriginal =
            new javax.swing.ImageIcon(getClass().getResource("/imagenes/tienda.png"));

        java.awt.Image img = iconoOriginal.getImage();
        java.awt.Image imgEscalada = img.getScaledInstance(
                lblLogo.getWidth(),
                lblLogo.getHeight(),
                java.awt.Image.SCALE_SMOOTH
        );

        lblLogo.setIcon(new javax.swing.ImageIcon(imgEscalada));
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        txtUsuario = new javax.swing.JTextField();
        txtPassword = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();
        lblLogo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 153, 255));

        jLabel1.setForeground(new java.awt.Color(0, 51, 51));
        jLabel1.setText("Usurario:");

        jLabel2.setForeground(new java.awt.Color(51, 51, 0));
        jLabel2.setText("Constraseña:");

        jButton1.setText("INGRESAR");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        txtUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsuarioActionPerformed(evt);
            }
        });

        txtPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPasswordActionPerformed(evt);
            }
        });

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Yu Gothic Medium", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 51));
        jLabel5.setText("Iniciar Sesión");

        lblLogo.setBackground(new java.awt.Color(200, 230, 255));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(187, 187, 187)
                            .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(63, 63, 63)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(118, 118, 118)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(57, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(84, 84, 84))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addComponent(jButton1)
                .addContainerGap(43, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsuarioActionPerformed

    private void txtPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPasswordActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
    String usuario = txtUsuario.getText().trim();
    String password = new String(txtPassword.getPassword()).trim();

    // Validar campos vacíos
    if (usuario.isEmpty() || password.isEmpty()) {
        JOptionPane.showMessageDialog(this,
                "Ingresa usuario y contraseña",
                "Campos incompletos",
                JOptionPane.WARNING_MESSAGE);
        return;
    }

    // ======= AQUI VA SOLO LA VALIDACIÓN CON BD =======
    UsuarioDAO dao = new UsuarioDAO();
   Usuario u = dao.buscarPorUsuarioYClave(usuario, password);

    if (u != null) {
        // Login OK
        JOptionPane.showMessageDialog(this,
                "¡Bienvenido " + u.getUsername() + " (" + u.getRol() + ")!",
                "Login exitoso",
                JOptionPane.INFORMATION_MESSAGE);

        // Abrir ventana según el rol
        if ("ADMIN".equalsIgnoreCase(u.getRol())) {
            administradores adminFrame = new administradores();
            centrarVentana(adminFrame);
            adminFrame.setVisible(true);
        } else {
            usuarioCompra compraFrame = new usuarioCompra();
            centrarVentana(compraFrame);
            compraFrame.setVisible(true);
        }

        // Cerrar login
        this.dispose();
    } else {
        // No encontró usuario en la BD
        JOptionPane.showMessageDialog(this,
                "Usuario o contraseña incorrectos",
                "Error de login",
                JOptionPane.ERROR_MESSAGE);
        txtPassword.setText("");
        txtUsuario.requestFocus();
    }
}

// Método para centrar ventanas
private void centrarVentana(java.awt.Window ventana) {
    ventana.setLocationRelativeTo(null); // Centrar en la pantalla
        
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    String usuarioTxt = txtUsuario.getText().trim();
    String claveTxt   = new String(txtPassword.getPassword()).trim(); // si usas JPasswordField

    if (usuarioTxt.isEmpty() || claveTxt.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this,
            "Ingresa usuario y contraseña.",
            "Datos incompletos",
            javax.swing.JOptionPane.WARNING_MESSAGE);
        return;
    }

    // 1) Consultar en BD
    Usuario u = usuarioDAO.buscarPorUsuarioYClave(usuarioTxt, claveTxt);

    if (u == null) {
        javax.swing.JOptionPane.showMessageDialog(this,
            "Usuario o contraseña incorrectos.",
            "Acceso denegado",
            javax.swing.JOptionPane.ERROR_MESSAGE);
        return;
    }

    // 2) Login correcto
    String nombreCliente = u.getUsername();  // por ahora usamos username
    String rol = u.getRol();                 // ADMIN o USUARIO

    // 3) Abrir ventana según rol
    if ("ADMIN".equalsIgnoreCase(rol)) {
        AdminInventarioFrame admin = new AdminInventarioFrame();
        admin.setVisible(true);
    } else {
        usuarioCompra2 frm = new usuarioCompra2(nombreCliente);
        frm.setVisible(true);
    }

    // 4) Cerrar login
    this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new acceso().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
