/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package capasPresentacion;

import Clases.Producto;
import Clasesdao.ProductoDAO;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
/**
 *
 * @author LAS
 */

public class administradores extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(administradores.class.getName());

    /**
     * Creates new form administradores
     */
    private List<Producto> listaProductos; // Lista para almacenar los productos
    private List<Producto> productosAgregados; // Lista para productos agregados temporalmente

    public administradores() {
    initComponents();
    cargarProductos(); 
    cargarCantidades(); 
    
    // Inicializar la lista temporal
    productosAgregados = new java.util.ArrayList<>();
    mostrarProductosEnTextArea(); // Mostrar lista vacía inicial
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnEliminarProducto = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cmbProductoAdmin = new javax.swing.JComboBox<>();
        cmbCantidad = new javax.swing.JComboBox<>();
        btnAgregar = new javax.swing.JButton();
        btnListar = new javax.swing.JButton();
        btnModificar1 = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        btnCargarInventario = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        txtAreaAdmin = new java.awt.TextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("ADMINISTRADORES");

        btnEliminarProducto.setText("Eliminar Producto");
        btnEliminarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarProductoActionPerformed(evt);
            }
        });

        jLabel2.setText("Producto");

        jLabel3.setText("Cantidad:");

        cmbProductoAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbProductoAdminActionPerformed(evt);
            }
        });

        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        btnListar.setText("Listar");
        btnListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarActionPerformed(evt);
            }
        });

        btnModificar1.setText("Modificar");
        btnModificar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificar1ActionPerformed(evt);
            }
        });

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        btnCargarInventario.setText("Cargar Inventario");
        btnCargarInventario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCargarInventarioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cmbProductoAdmin, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cmbCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnModificar1, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE)
                            .addComponent(btnAgregar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addComponent(btnEliminarProducto)
                        .addGap(42, 42, 42)
                        .addComponent(btnListar, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(173, 173, 173)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(173, 173, 173)
                        .addComponent(btnCargarInventario)))
                .addContainerGap(92, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jSeparator3, javax.swing.GroupLayout.DEFAULT_SIZE, 450, Short.MAX_VALUE)
                        .addComponent(jSeparator2))
                    .addComponent(txtAreaAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 441, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(cmbProductoAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(btnAgregar)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(cmbCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(btnModificar1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBuscar)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtAreaAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEliminarProducto)
                    .addComponent(btnListar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(btnCargarInventario)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarActionPerformed
         if (productosAgregados == null || productosAgregados.isEmpty()) {
        txtAreaAdmin.setText("🛒 CARRITO DE COMPRAS\n\n" +
                           "No hay productos agregados al carrito.\n\n" +
                           "📝 Instrucciones:\n" +
                           "1. Selecciona un producto del ComboBox\n" +
                           "2. Selecciona una cantidad\n" +
                           "3. Haz clic en 'Agregar'");
        return;
    }
    
    StringBuilder contenido = new StringBuilder();
    contenido.append("🛒 CARRITO DE COMPRAS - PRODUCTOS AGREGADOS\n\n");
    
    double totalCompra = 0.0;
    int totalItems = 0;
    
    for (Producto producto : productosAgregados) {
        double precio = producto.getPrecioProducto().doubleValue();
        int cantidad = producto.getStock(); // Usamos stock como cantidad temporal
        double subtotal = precio * cantidad;
        
        contenido.append(String.format("🏷️ %s\n", producto.getNombre()));
        contenido.append(String.format("   Cantidad: %d\n", cantidad));
        contenido.append(String.format("   Precio unitario: $%.2f\n", precio));
        contenido.append(String.format("   Subtotal: $%.2f\n", subtotal));
        contenido.append("   --------------------\n");
        
        totalCompra += subtotal;
        totalItems += cantidad;
    }
    
    // Calcular impuestos
    double iva = totalCompra * 0.19;
    double totalFinal = totalCompra + iva;
    
    contenido.append("\n📊 RESUMEN:\n");
    contenido.append(String.format("• Productos diferentes: %d\n", productosAgregados.size()));
    contenido.append(String.format("• Total items: %d\n", totalItems));
    contenido.append(String.format("• Subtotal: $%.2f\n", totalCompra));
    contenido.append(String.format("• IVA (19%%): $%.2f\n", iva));
    contenido.append(String.format("• TOTAL: $%.2f\n", totalFinal));
    
    txtAreaAdmin.setText(contenido.toString());
    System.out.println("TextArea actualizado con " + productosAgregados.size() + " productos agregados");
    }//GEN-LAST:event_btnListarActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        // TODO add your handling code here:
   try {
        // Verificar que hay productos cargados
        if (listaProductos == null || listaProductos.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, 
                "No hay productos disponibles en la BD", 
                "Error", 
                javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        // Obtener el producto seleccionado
        int indiceSeleccionado = cmbProductoAdmin.getSelectedIndex();
        if (indiceSeleccionado == -1) {
            javax.swing.JOptionPane.showMessageDialog(this, 
                "Seleccione un producto", 
                "Error", 
                javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        Producto productoSelBD = listaProductos.get(indiceSeleccionado);
        
        // Obtener la cantidad seleccionada
        String cantidadStr = cmbCantidad.getSelectedItem().toString();
        int cantidad = Integer.parseInt(cantidadStr);
        
        // Crear una copia del producto con la cantidad seleccionada
        Producto productoAgregar = new Producto();
        productoAgregar.setIdproducto(productoSelBD.getIdproducto());
        productoAgregar.setNombre(productoSelBD.getNombre());
        productoAgregar.setPrecioProducto(productoSelBD.getPrecioProducto());
        productoAgregar.setStock(cantidad); // Usamos stock para guardar la cantidad temporal
        
        // Agregar a la lista temporal
        productosAgregados.add(productoAgregar);
        
        // Mostrar confirmación
        double subtotal = productoSelBD.getPrecioProducto().doubleValue() * cantidad;
        String mensaje = String.format("✅ Producto agregado al carrito:\n\n" +
            "📦 Producto: %s\n" +
            "🔢 Cantidad: %d\n" +
            "💰 Precio unitario: $%.2f\n" +
            "💵 Subtotal: $%.2f",
            productoSelBD.getNombre(),
            cantidad,
            productoSelBD.getPrecioProducto().doubleValue(),
            subtotal);
        
        javax.swing.JOptionPane.showMessageDialog(this, mensaje, "Producto Agregado", javax.swing.JOptionPane.INFORMATION_MESSAGE);
        
        // Actualizar el TextArea con los productos agregados
        mostrarProductosEnTextArea();
        
    } catch (Exception e) {
        javax.swing.JOptionPane.showMessageDialog(this, 
            "❌ Error al agregar producto: " + e.getMessage(), 
            "Error", 
            javax.swing.JOptionPane.ERROR_MESSAGE);
        e.printStackTrace();
    }
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void cmbProductoAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbProductoAdminActionPerformed
        // TODO add your handling code here:
            // Verificar qué producto se seleccionó
    if (cmbProductoAdmin.getSelectedIndex() != -1 && listaProductos != null) {
        Producto productoSeleccionado = listaProductos.get(cmbProductoAdmin.getSelectedIndex());
        
        // Mostrar información del producto seleccionado (opcional)
        System.out.println("Producto seleccionado: " + productoSeleccionado.getNombre());
        System.out.println("Precio: " + productoSeleccionado.getPrecioProducto());
        System.out.println("Stock: " + productoSeleccionado.getStock());
    }
    }//GEN-LAST:event_cmbProductoAdminActionPerformed

    private void btnEliminarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarProductoActionPerformed
          // Limpiar todos los productos agregados
    if (productosAgregados != null && !productosAgregados.isEmpty()) {
        int confirmacion = javax.swing.JOptionPane.showConfirmDialog(this, 
            "¿Está seguro de eliminar todos los productos del carrito?\n" +
            "Total de productos: " + productosAgregados.size(),
            "Confirmar Eliminación", 
            javax.swing.JOptionPane.YES_NO_OPTION);
        
        if (confirmacion == javax.swing.JOptionPane.YES_OPTION) {
            productosAgregados.clear();
            mostrarProductosEnTextArea();
            javax.swing.JOptionPane.showMessageDialog(this, 
                "✅ Carrito vaciado correctamente", 
                "Carrito Vacío", 
                javax.swing.JOptionPane.INFORMATION_MESSAGE);
        }
    } else {
        javax.swing.JOptionPane.showMessageDialog(this, 
            "El carrito ya está vacío", 
            "Carrito Vacío", 
            javax.swing.JOptionPane.INFORMATION_MESSAGE);
    }
    }//GEN-LAST:event_btnEliminarProductoActionPerformed

    private void btnModificar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificar1ActionPerformed
        // TODO add your handling code here:
    javax.swing.JOptionPane.showMessageDialog(this, 
        "Funcionalidad de modificar producto", 
        "Modificar Producto", 
        javax.swing.JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnModificar1ActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
              javax.swing.JOptionPane.showMessageDialog(this, 
        "Funcionalidad de buscar producto", 
        "Buscar Producto", 
        javax.swing.JOptionPane.INFORMATION_MESSAGE);

    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnCargarInventarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCargarInventarioActionPerformed
        // TODO add your handling code here:
           // Recargar productos desde la BD
    cargarProductos();
    mostrarProductosEnTextArea();
    javax.swing.JOptionPane.showMessageDialog(this, 
        "✅ Inventario actualizado", 
        "Inventario Actualizado", 
        javax.swing.JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnCargarInventarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new administradores().setVisible(true));
    }
    private void cargarProductos() {
    try {
        System.out.println("=== CARGANDO PRODUCTOS ===");
        
        ProductoDAO productoDAO = new ProductoDAO();
        listaProductos = productoDAO.listarTodos(); // Guardar la lista completa
        
        System.out.println("Productos encontrados: " + (listaProductos != null ? listaProductos.size() : "NULL"));
        
        // Crear un modelo para el comboBox
        DefaultComboBoxModel<String> modeloCombo = new DefaultComboBoxModel<>();
        
        // Llenar el comboBox con los nombres de los productos
        if (listaProductos != null && !listaProductos.isEmpty()) {
            for (Producto producto : listaProductos) {
                modeloCombo.addElement(producto.getNombre());
                System.out.println("Agregado: " + producto.getNombre());
            }
        } else {
            modeloCombo.addElement("-- No hay productos --");
            System.out.println("No hay productos en la BD");
        }

        // Establecer el modelo al JComboBox
        cmbProductoAdmin.setModel(modeloCombo);
        System.out.println("ComboBox actualizado");
        
    } catch (Exception e) {
        System.out.println("ERROR en cargarProductos: " + e.getMessage());
        e.printStackTrace();
        javax.swing.JOptionPane.showMessageDialog(this, 
            "Error al cargar productos: " + e.getMessage(), 
            "Error", 
            javax.swing.JOptionPane.ERROR_MESSAGE);
    }
}

// Método para cargar cantidades en el ComboBox
private void cargarCantidades() {
    DefaultComboBoxModel<String> modeloCantidades = new DefaultComboBoxModel<>();
    
    // Agregar cantidades del 1 al 50
    for (int i = 1; i <= 50; i++) {
        modeloCantidades.addElement(String.valueOf(i));
    }
    
    cmbCantidad.setModel(modeloCantidades);
    System.out.println("Cantidades cargadas: 1-50");
}

// Método para mostrar productos en el TextArea
private void mostrarProductosEnTextArea() {
    if (listaProductos == null || listaProductos.isEmpty()) {
        txtAreaAdmin.setText("No hay productos en el inventario");
        return;
    }
    
    StringBuilder contenido = new StringBuilder();
    contenido.append("=== INVENTARIO DE PRODUCTOS ===\n\n");
    
    for (Producto producto : listaProductos) {
        contenido.append(String.format("🏷️ %s\n", producto.getNombre()));
        contenido.append(String.format("   ID: %d\n", producto.getIdproducto()));
        contenido.append(String.format("   Precio: $%.2f\n", producto.getPrecioProducto().doubleValue()));
        contenido.append(String.format("   Stock: %d\n", producto.getStock()));
        contenido.append("   --------------------\n");
    }
    
    contenido.append(String.format("\nTotal de productos: %d", listaProductos.size()));
    
    txtAreaAdmin.setText(contenido.toString());
    System.out.println("TextArea actualizado");
}
    
// Método para cargar productos desde la BD en el ComboBox
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCargarInventario;
    private javax.swing.JButton btnEliminarProducto;
    private javax.swing.JButton btnListar;
    private javax.swing.JButton btnModificar1;
    private javax.swing.JComboBox<String> cmbCantidad;
    private javax.swing.JComboBox<String> cmbProductoAdmin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private java.awt.TextArea txtAreaAdmin;
    // End of variables declaration//GEN-END:variables
}
