/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package capasPresentacion;
import Clases.Producto;
import Clasesdao.ProductoDAO;
import java.math.BigDecimal;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.DefaultComboBoxModel;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.math.BigDecimal;
import javax.swing.JMenuBar;
import javax.swing.JMenu;
import javax.swing.JMenuItem;


/**
 *
 * @author marci
 */
public class AdminInventarioFrame extends javax.swing.JFrame {
    
    
    private ProductoDAO productoDAO;
    private List<Producto> listaProductos;
    private int stockAnterior;
    

    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AdminInventarioFrame.class.getName());

    /**
     * Creates new form AdminInventarioFrame
     */
  public AdminInventarioFrame() {
    initComponents();
    setLocationRelativeTo(null);
    productoDAO = new ProductoDAO();
    cargarProductos();            
    configurarTablaHistorial();   
    configurarListaColores();   
    personalizarUI();
    estilizarBotones();
     crearMenuAdmin();
    
   

    // --- Cuando cambias de producto en la lista de la izquierda ---
    lstProductos.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
        @Override
        public void valueChanged(javax.swing.event.ListSelectionEvent e) {
            // Para que no se dispare dos veces
            if (e.getValueIsAdjusting()) {
                return;
            }

            int idx = lstProductos.getSelectedIndex();
            if (idx >= 0 && idx < listaProductos.size()) {
                Producto seleccionado = listaProductos.get(idx);
                mostrarDetallesProducto(seleccionado);   // llena nombre, stock, precio, activo/descont.
            }
        }
    });

    // --- Cuando cambias el nombre en el combo ---
    cmbNombre.addActionListener(new java.awt.event.ActionListener() {
        @Override
        public void actionPerformed(java.awt.event.ActionEvent e) {
            int idx = cmbNombre.getSelectedIndex();
            if (idx >= 0 && idx < listaProductos.size()) {
                Producto seleccionado = listaProductos.get(idx);

                // Mostrar detalles de ese producto
                mostrarDetallesProducto(seleccionado);

                // Sincronizar la selección de la lista de la izquierda
                lstProductos.setSelectedIndex(idx);
            }
        }
    });

    // --- Que solo uno de los dos checkboxes esté marcado ---

    chkActivo.addActionListener(new java.awt.event.ActionListener() {
        @Override
        public void actionPerformed(java.awt.event.ActionEvent e) {
            if (chkActivo.isSelected()) {
                chkDescontinuad.setSelected(false);
            } else {
                chkDescontinuad.setSelected(true);
            }
        }
    });

    chkDescontinuad.addActionListener(new java.awt.event.ActionListener() {
        @Override
        public void actionPerformed(java.awt.event.ActionEvent e) {
            if (chkDescontinuad.isSelected()) {
                chkActivo.setSelected(false);
            } else {
                chkActivo.setSelected(true);
            }
        }
    });
}

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelMain = new javax.swing.JPanel();
        panelProductos = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtBuscar = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstProductos = new javax.swing.JList<>();
        btnNuevoProducto = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        chkDescontinuado = new javax.swing.JPanel();
        JdetallesProducto = new javax.swing.JLabel();
        cmbNombre = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        chkActivo = new javax.swing.JCheckBox();
        chkDescontinuad = new javax.swing.JCheckBox();
        btnGuardar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        panelHistorial = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblHistorial = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtAgregarStock = new javax.swing.JTextField();
        txtCantidadStock = new javax.swing.JTextField();
        txtPrecioUnitario = new javax.swing.JTextField();
        btnAgregarStock = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        txtRegistrarVenta = new javax.swing.JTextField();
        btnRegistrarVenta = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelMain.setBackground(new java.awt.Color(204, 204, 204));

        panelProductos.setBackground(new java.awt.Color(255, 255, 255));
        panelProductos.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 204, 204)));

        jLabel1.setText("PRODUCTOS");

        txtBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscarActionPerformed(evt);
            }
        });

        lstProductos.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(lstProductos);

        btnNuevoProducto.setText("Nuevo Producto");
        btnNuevoProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoProductoActionPerformed(evt);
            }
        });

        jLabel8.setText("Buscar");

        javax.swing.GroupLayout panelProductosLayout = new javax.swing.GroupLayout(panelProductos);
        panelProductos.setLayout(panelProductosLayout);
        panelProductosLayout.setHorizontalGroup(
            panelProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelProductosLayout.createSequentialGroup()
                .addGroup(panelProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelProductosLayout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(btnNuevoProducto))
                    .addGroup(panelProductosLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(panelProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        panelProductosLayout.setVerticalGroup(
            panelProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelProductosLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 583, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(btnNuevoProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(199, Short.MAX_VALUE))
        );

        chkDescontinuado.setBackground(new java.awt.Color(255, 255, 255));
        chkDescontinuado.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 204, 204)));

        JdetallesProducto.setText("DETALLES DEL PRODUCUTO");

        cmbNombre.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel2.setText("Nombre");

        chkActivo.setText("Activo");

        chkDescontinuad.setText("Descontinuado");
        chkDescontinuad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkDescontinuadActionPerformed(evt);
            }
        });

        btnGuardar.setText("GUARDAR CAMBIOS");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnEliminar.setText("ELIMINAR");

        panelHistorial.setBackground(new java.awt.Color(255, 255, 255));
        panelHistorial.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 204, 204)));

        tblHistorial.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Fecha", "Tipo", "Cantidad", "Usuario"
            }
        ));
        jScrollPane3.setViewportView(tblHistorial);

        javax.swing.GroupLayout panelHistorialLayout = new javax.swing.GroupLayout(panelHistorial);
        panelHistorial.setLayout(panelHistorialLayout);
        panelHistorialLayout.setHorizontalGroup(
            panelHistorialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelHistorialLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 646, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelHistorialLayout.setVerticalGroup(
            panelHistorialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelHistorialLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 516, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jLabel3.setText("Cantidad en stock");

        jLabel4.setText("Precio Unitario");

        jLabel6.setText("Añadir stock (unidades)");

        btnAgregarStock.setText("Añadir stock");
        btnAgregarStock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarStockActionPerformed(evt);
            }
        });

        jLabel7.setText("Registar venta (unidades)");

        btnRegistrarVenta.setText("Registrar venta");
        btnRegistrarVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarVentaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout chkDescontinuadoLayout = new javax.swing.GroupLayout(chkDescontinuado);
        chkDescontinuado.setLayout(chkDescontinuadoLayout);
        chkDescontinuadoLayout.setHorizontalGroup(
            chkDescontinuadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(chkDescontinuadoLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(chkDescontinuadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(chkDescontinuadoLayout.createSequentialGroup()
                        .addGroup(chkDescontinuadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnGuardar)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(515, 515, Short.MAX_VALUE))
                    .addGroup(chkDescontinuadoLayout.createSequentialGroup()
                        .addGroup(chkDescontinuadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(chkDescontinuadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(JdetallesProducto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(cmbNombre, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(chkDescontinuadoLayout.createSequentialGroup()
                                    .addGroup(chkDescontinuadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(chkActivo, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtCantidadStock, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(84, 84, 84)
                                    .addGroup(chkDescontinuadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(chkDescontinuadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(txtAgregarStock, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(chkDescontinuad, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addComponent(btnAgregarStock, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPrecioUnitario, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(chkDescontinuadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtRegistrarVenta)
                            .addComponent(btnRegistrarVenta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(124, 124, 124))))
            .addGroup(chkDescontinuadoLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(panelHistorial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        chkDescontinuadoLayout.setVerticalGroup(
            chkDescontinuadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(chkDescontinuadoLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(JdetallesProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmbNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(chkDescontinuadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(chkDescontinuadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtCantidadStock, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                    .addComponent(txtAgregarStock)
                    .addComponent(txtRegistrarVenta, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(chkDescontinuadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPrecioUnitario, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAgregarStock, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRegistrarVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(chkDescontinuadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(chkDescontinuad, javax.swing.GroupLayout.DEFAULT_SIZE, 52, Short.MAX_VALUE)
                    .addComponent(chkActivo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(29, 29, 29)
                .addGroup(chkDescontinuadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addComponent(panelHistorial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout panelMainLayout = new javax.swing.GroupLayout(panelMain);
        panelMain.setLayout(panelMainLayout);
        panelMainLayout.setHorizontalGroup(
            panelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMainLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(panelProductos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(chkDescontinuado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(53, Short.MAX_VALUE))
        );
        panelMainLayout.setVerticalGroup(
            panelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelMainLayout.createSequentialGroup()
                .addContainerGap(39, Short.MAX_VALUE)
                .addGroup(panelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelProductos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chkDescontinuado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscarActionPerformed
          String texto = txtBuscar.getText().trim().toLowerCase();

    if (texto.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(
                this,
                "Escribe algo para buscar.",
                "Buscar",
                javax.swing.JOptionPane.WARNING_MESSAGE
        );
        return;
    }

    int encontrado = -1;

    // Buscar en listaProductos por nombre
    for (int i = 0; i < listaProductos.size(); i++) {
        Producto p = listaProductos.get(i);
        if (p.getNombre().toLowerCase().contains(texto)) {
            encontrado = i;
            break;
        }
    }

    if (encontrado == -1) {
        javax.swing.JOptionPane.showMessageDialog(
                this,
                "No se encontró ningún producto con: " + texto,
                "Sin resultados",
                javax.swing.JOptionPane.INFORMATION_MESSAGE
        );
    } else {
        // Seleccionar en la lista y en el combo
        lstProductos.setSelectedIndex(encontrado);
        lstProductos.ensureIndexIsVisible(encontrado);
        cmbNombre.setSelectedIndex(encontrado);
    }
    }//GEN-LAST:event_txtBuscarActionPerformed

    private void chkDescontinuadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkDescontinuadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkDescontinuadActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
      int indice = lstProductos.getSelectedIndex();
    if (indice < 0 || indice >= listaProductos.size()) {
        JOptionPane.showMessageDialog(this,
                "Selecciona un producto de la lista primero.",
                "Aviso",
                JOptionPane.WARNING_MESSAGE);
        return;
    }

    // 2) Tomar el producto real de la lista (tiene el idproducto correcto)
    Producto p = listaProductos.get(indice);

    // 3) Leer los datos de los campos de la pantalla
    try {
        // Nombre: si lo editas en un JTextField, usa ese; si es solo de lectura, puedes dejar p.getNombre()
        // Aquí supongo que lo editas en un combo de nombre (cmbNombre) o en txtNombre
        String nuevoNombre = cmbNombre.getSelectedItem().toString().trim();
        if (nuevoNombre.isEmpty()) {
            JOptionPane.showMessageDialog(this,
                    "El nombre del producto no puede estar vacío.",
                    "Datos inválidos",
                    JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Precio
        String precioStr = txtPrecioUnitario.getText().trim();
        if (precioStr.isEmpty()) {
            JOptionPane.showMessageDialog(this,
                    "Ingresa un precio válido.",
                    "Datos inválidos",
                    JOptionPane.ERROR_MESSAGE);
            return;
        }
        java.math.BigDecimal precio = new java.math.BigDecimal(precioStr);

        // Stock
        String stockStr = txtCantidadStock.getText().trim();
        int stock;
        try {
            stock = Integer.parseInt(stockStr);
            if (stock < 0) {
                throw new NumberFormatException("stock negativo");
            }
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this,
                    "La cantidad en stock debe ser un número entero mayor o igual a 0.",
                    "Datos inválidos",
                    JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Activo / descontinuado
        boolean activo = chkActivo.isSelected() && !chkDescontinuad.isSelected();

        // 4) Actualizar el objeto Producto con estos datos
        p.setNombre(nuevoNombre);
        p.setPrecioProducto(precio);
        p.setStock(stock);
        p.setActivo(activo);

        // 5) Llamar al DAO para actualizar en la BD
        boolean ok = productoDAO.actualizar(p);

        if (ok) {
            JOptionPane.showMessageDialog(this,
                    "Producto actualizado correctamente.",
                    "Éxito",
                    JOptionPane.INFORMATION_MESSAGE);

            // 6) Recargar la lista desde la BD para reflejar cambios
            listaProductos = productoDAO.listarTodos();
            refrescarListaProductos();   // método que vuelve a llenar lstProductos
            // Si quieres, también puedes volver a seleccionar el producto actualizado.
        } else {
            JOptionPane.showMessageDialog(this,
                    "No se pudo actualizar el producto.",
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
        }

    } catch (Exception e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(this,
                "Ocurrió un error al guardar: " + e.getMessage(),
                "Error",
                JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnAgregarStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarStockActionPerformed
        int idx = lstProductos.getSelectedIndex();
    if (idx == -1) {
        JOptionPane.showMessageDialog(this, "Selecciona un producto de la lista.", "Aviso", JOptionPane.WARNING_MESSAGE);
        return;
    }

    Producto seleccionado = listaProductos.get(idx);

    // 2. Leer cuántas unidades queremos añadir
    int cantidadASumar;
    try {
        cantidadASumar = Integer.parseInt(txtAgregarStock.getText().trim());
    } catch (NumberFormatException ex) {
        JOptionPane.showMessageDialog(this, "Ingrese una cantidad válida para añadir stock.", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

    if (cantidadASumar <= 0) {
        JOptionPane.showMessageDialog(this, "La cantidad a añadir debe ser mayor a cero.", "Aviso", JOptionPane.WARNING_MESSAGE);
        return;
    }

    // 3. Llamar al DAO: agregarStock(idProducto, cantidadASumar)
    // Ajusta getIdproducto() al getter real de tu clase Producto
    int idProducto = seleccionado.getIdproducto();  // cámbialo si tu getter se llama distinto

    boolean ok = productoDAO.agregarStock(idProducto, cantidadASumar);

    if (!ok) {
        JOptionPane.showMessageDialog(this, "Error al agregar stock en la base de datos.", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

    // 4. Actualizar el stock en pantalla y el stockAnterior
    int nuevoStock = stockAnterior + cantidadASumar;
    stockAnterior = nuevoStock;
    txtCantidadStock.setText(String.valueOf(nuevoStock));
    
    actualizarEstadoBotonVenta();
    limpiarCamposMovimiento();

    // 5. Registrar movimiento en el historial
    DefaultTableModel modeloHist = (DefaultTableModel) tblHistorial.getModel();

    String fecha = LocalDateTime.now()
            .format(DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm"));

    String tipoMovimiento = "ENTRADA";     // llegó stock del distribuidor
    String usuario = "admin";              // luego puedes poner el usuario logueado

    String nombreProducto = seleccionado.getNombre(); // ajusta getter si se llama distinto

    modeloHist.addRow(new Object[]{
    fecha,
    nombreProducto,
    tipoMovimiento,
    cantidadASumar,
    usuario
    });
    // 6. Limpiar el campo de añadir
    txtAgregarStock.setText("");

    // 7. Opcional: refrescar lista/combo
    cargarProductos();
    actualizarEstadoBotonVenta();
    }//GEN-LAST:event_btnAgregarStockActionPerformed

    private void btnRegistrarVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarVentaActionPerformed
         int idx = lstProductos.getSelectedIndex();
    if (idx == -1) {
        JOptionPane.showMessageDialog(this, "Selecciona un producto de la lista.", "Aviso", JOptionPane.WARNING_MESSAGE);
        return;
    }

    Producto seleccionado = listaProductos.get(idx);

    // 2. Leer cuántas unidades queremos vender
    int cantidadAVender;
    try {
        cantidadAVender = Integer.parseInt(txtRegistrarVenta.getText().trim());
    } catch (NumberFormatException ex) {
        JOptionPane.showMessageDialog(this, "Ingrese una cantidad válida para la venta.", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

    if (cantidadAVender <= 0) {
        JOptionPane.showMessageDialog(this, "La cantidad a vender debe ser mayor a cero.", "Aviso", JOptionPane.WARNING_MESSAGE);
        return;
    }

    // 3. Verificar que haya stock suficiente
    if (cantidadAVender > stockAnterior) {
        JOptionPane.showMessageDialog(this, "No hay stock suficiente para esta venta.", "Aviso", JOptionPane.WARNING_MESSAGE);
        return;
    }

    // 4. Calcular nuevo stock
    int nuevoStock = stockAnterior - cantidadAVender;

    // 5. Actualizar en BD
    //    Aquí reaprovechamos la misma idea que antes: un método en el DAO
    //    que ponga el stock exacto. Si ya pusiste uno para aumentar stock exacto,
    //    úsalo aquí también. Si no, puedes usar 'actualizar(Producto p)'.

    // OPCIÓN A: si tienes un método tipo actualizarStock(id, nuevoStock)
    // boolean ok = productoDAO.actualizarStock(seleccionado.getIdproducto(), nuevoStock);

    // OPCIÓN B: usar el 'actualizar(Producto p)' que aparece en tu autocompletado:
    seleccionado.setStock(nuevoStock); // necesitas tener setStock en Producto
    boolean ok = productoDAO.actualizar(seleccionado);

    if (!ok) {
        JOptionPane.showMessageDialog(this, "Error al registrar la venta en la base de datos.", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

    // 6. Actualizar stockAnterior y el campo visual
    stockAnterior = nuevoStock;
    txtCantidadStock.setText(String.valueOf(nuevoStock));
    
    actualizarEstadoBotonVenta();
    limpiarCamposMovimiento();

    // 7. Registrar movimiento en el historial
    DefaultTableModel modeloHist = (DefaultTableModel) tblHistorial.getModel();

    String fecha = LocalDateTime.now()
            .format(DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm"));

    String tipoMovimiento = "SALIDA";      // venta
    String usuario = "admin";              // o el usuario logueado

    String nombreProducto = seleccionado.getNombre(); // mismo getter que antes

    modeloHist.addRow(new Object[]{
    fecha,
    nombreProducto,
    tipoMovimiento,
    cantidadAVender,
    usuario
    });

    // 8. Limpiar el campo de venta
    txtRegistrarVenta.setText("");

    // 9. Refrescar lista de productos
    cargarProductos();
    actualizarEstadoBotonVenta();
    }//GEN-LAST:event_btnRegistrarVentaActionPerformed

    private void btnNuevoProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoProductoActionPerformed
         String nombre = JOptionPane.showInputDialog(this, "Nombre del nuevo producto:");
    if (nombre == null) {
        // canceló
        return;
    }
    nombre = nombre.trim();
    if (nombre.isEmpty()) {
        JOptionPane.showMessageDialog(this, "El nombre no puede estar vacío.", "Aviso", JOptionPane.WARNING_MESSAGE);
        return;
    }

    // 2. Pedir stock inicial
    String stockStr = JOptionPane.showInputDialog(this, "Stock inicial (unidades):", "0");
    if (stockStr == null) return;
    int stockInicial;
    try {
        stockInicial = Integer.parseInt(stockStr.trim());
    } catch (NumberFormatException ex) {
        JOptionPane.showMessageDialog(this, "Cantidad de stock inválida.", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }
    if (stockInicial < 0) {
        JOptionPane.showMessageDialog(this, "El stock inicial no puede ser negativo.", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

    // 3. Pedir precio
    String precioStr = JOptionPane.showInputDialog(this, "Precio unitario:", "0.00");
    if (precioStr == null) return;

    BigDecimal precioBD;
    try {
        precioBD = new BigDecimal(precioStr.trim().replace(",", ".")); // 👈 AQUÍ se crea el BigDecimal
    } catch (NumberFormatException ex) {
        JOptionPane.showMessageDialog(this, "Precio inválido.", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

    // 4. Crear el objeto Producto
    Producto nuevo = new Producto();
    nuevo.setNombre(nombre);      // ajusta estos setters si tus nombres son distintos
    nuevo.setStock(stockInicial);
    nuevo.setPrecioProducto(precioBD);

    // 5. Insertar en BD
    boolean ok = productoDAO.insertar(nuevo);
    if (!ok) {
        JOptionPane.showMessageDialog(this, "Error al insertar el producto en la base de datos.", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

    // 6. Recargar la lista y el combo (NO borra, solo vuelve a leer todo, ahora con el nuevo)
    cargarProductos();

    JOptionPane.showMessageDialog(this, "Producto añadido correctamente.");
    }//GEN-LAST:event_btnNuevoProductoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new AdminInventarioFrame().setVisible(true));
    }
private void cargarProductos() {
    // Pedimos todos los productos al DAO
    listaProductos = productoDAO.listarTodos();

    javax.swing.DefaultListModel<String> modeloLista = new javax.swing.DefaultListModel<>();
    javax.swing.DefaultComboBoxModel<String> modeloCombo = new javax.swing.DefaultComboBoxModel<>();

    for (Producto p : listaProductos) {
        modeloLista.addElement(p.getNombre());  // para la lista de la izquierda
        modeloCombo.addElement(p.getNombre());  // para el combo "Nombre"
    }

    // Conectamos los modelos
    lstProductos.setModel(modeloLista);
    cmbNombre.setModel(modeloCombo);

    // Seleccionamos el primero para que se vea algo desde el inicio
    if (!listaProductos.isEmpty()) {
        lstProductos.setSelectedIndex(0);
    }

    System.out.println("Productos cargados: " + listaProductos.size());
}




    
    private void configurarListaColores() {
    lstProductos.setCellRenderer(new javax.swing.DefaultListCellRenderer() {
        @Override
        public java.awt.Component getListCellRendererComponent(
                javax.swing.JList<?> list,
                Object value,
                int index,
                boolean isSelected,
                boolean cellHasFocus) {

            javax.swing.JLabel label = (javax.swing.JLabel) super.getListCellRendererComponent(
                    list, value, index, isSelected, cellHasFocus);

            // Por seguridad: verificamos que el índice exista en la lista
            if (index >= 0 && index < listaProductos.size()) {
                Clases.Producto p = listaProductos.get(index);

                if (p.getStock() <= 0) {
                    // SIN stock → rojo
                    if (!isSelected) {
                        label.setForeground(java.awt.Color.RED);
                        label.setBackground(java.awt.Color.WHITE);
                    } else {
                        label.setForeground(java.awt.Color.WHITE);
                        label.setBackground(new java.awt.Color(200, 0, 0));
                    }
                } else {
                    // CON stock → verde
                    if (!isSelected) {
                        label.setForeground(new java.awt.Color(0, 128, 0)); // verde oscuro
                        label.setBackground(java.awt.Color.WHITE);
                    } else {
                        label.setForeground(java.awt.Color.WHITE);
                        label.setBackground(new java.awt.Color(0, 153, 0));
                    }
                }
            }

            return label;
        }
    });
}

    
    private void mostrarDetallesProducto(Producto p) {
    if (p == null) return;

    // Nombre
    cmbNombre.setSelectedItem(p.getNombre());  // ajusta getNombre() si se llama distinto

    // Cantidad en stock
    txtCantidadStock.setText(String.valueOf(p.getStock())); // ajusta getStock()
    txtPrecioUnitario.setText(String.valueOf(p.getPrecioProducto()));
    
    stockAnterior = p.getStock();

    limpiarCamposMovimiento();              
    actualizarEstadoBotonVenta(); 
    
    chkActivo.setSelected(p.isActivo());
    chkDescontinuad.setSelected(!p.isActivo());
    actualizarEstadoBotonVenta();
}
    
    private void configurarTablaHistorial() {
        
        javax.swing.table.JTableHeader header = tblHistorial.getTableHeader();
    header.setOpaque(true);
    header.setBackground(new java.awt.Color(40, 40, 40)); // azul
     header.setForeground(java.awt.Color.BLACK);             // texto blanco
    header.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 12));
     DefaultTableModel modelo = new DefaultTableModel(
        new Object[]{"Fecha", "Producto", "Tipo", "Cantidad", "Usuario"}, 0
    ) {
        @Override
        public boolean isCellEditable(int row, int column) {
            return false;
        }
    };

    tblHistorial.setModel(modelo);
}
    
    private void limpiarCamposMovimiento() {
    txtAgregarStock.setText("");
    txtRegistrarVenta.setText("");
}

   private void actualizarEstadoBotonVenta() {
    int idx = lstProductos.getSelectedIndex();
    if (idx < 0 || idx >= listaProductos.size()) {
        btnRegistrarVenta.setEnabled(false);
        return;
    }

    Producto p = listaProductos.get(idx);

    boolean activo = p.isActivo();
    int stock = p.getStock();

    // Solo permitir venta si está activo y tiene stock > 0
    boolean puedeVender = activo && stock > 0;

    btnRegistrarVenta.setEnabled(puedeVender);
}
   private void personalizarUI() {
    // Paleta de colores (puedes ajustar valores)
    java.awt.Color azulFondo   = new java.awt.Color(214, 234, 248);  // Fondo general
    java.awt.Color grisPanel   = java.awt.Color.WHITE;               // Paneles blancos
    
    
    


    // 1) Fondo del frame y panel principal
    getContentPane().setBackground(azulFondo);
    panelMain.setBackground(azulFondo);

    // 2) Paneles internos
    panelProductos.setBackground(grisPanel);
    panelHistorial.setBackground(grisPanel);
    chkDescontinuado.setBackground(grisPanel);

    // 3) Labels - tipografías
    java.awt.Font titulo = new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 18);
    java.awt.Font seccion = new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 13);
    java.awt.Font texto = new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 12);

    JdetallesProducto.setFont(titulo);                // por ejemplo: "DETALLES DEL PRODUCTO"
    JdetallesProducto.setForeground(new java.awt.Color(33, 33, 33));

    jLabel1.setFont(seccion);           // "PRODUCTOS"
    

    // El resto de labels
    javax.swing.JLabel[] labels = {
        jLabel2, jLabel3, jLabel6,
        jLabel4, jLabel7,
        
    };
    for (javax.swing.JLabel l : labels) {
        if (l != null) {
            l.setFont(texto);
            l.setForeground(new java.awt.Color(60, 60, 60));
        }
    }

    // 4) Campos de texto
    javax.swing.JTextField[] textos = {
        txtCantidadStock, txtAgregarStock, txtPrecioUnitario, txtRegistrarVenta
    };
    javax.swing.border.Border bordeCampo =
        javax.swing.BorderFactory.createCompoundBorder(
            javax.swing.BorderFactory.createLineBorder(new java.awt.Color(200, 200, 200)),
            javax.swing.BorderFactory.createEmptyBorder(2, 4, 2, 4)
        );

    for (javax.swing.JTextField t : textos) {
        if (t != null) {
            t.setFont(texto);
            t.setBorder(bordeCampo);
        }
    }

    // 5) Combo y lista de productos
    cmbNombre.setFont(texto);
    cmbNombre.setBackground(java.awt.Color.WHITE);

    lstProductos.setFont(texto);
   
    lstProductos.setSelectionForeground(java.awt.Color.WHITE);

   
    // 8) Tabla de historial
    // 8) Tabla de historial
javax.swing.table.JTableHeader header = tblHistorial.getTableHeader();

   
    header.setForeground(java.awt.Color.BLACK);
    header.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 12));

    tblHistorial.setFont(texto);
    tblHistorial.setRowHeight(22);
    tblHistorial.setGridColor(new java.awt.Color(224, 224, 224));
    tblHistorial.setSelectionBackground(new java.awt.Color(187, 222, 251));
    tblHistorial.setSelectionForeground(new java.awt.Color(33, 33, 33));

    // 9) Bordes tipo tarjeta para los paneles
    panelProductos.setBorder(
        javax.swing.BorderFactory.createCompoundBorder(
            javax.swing.BorderFactory.createTitledBorder("  Productos"),
            javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5)
        )
    );

    panelHistorial.setBorder(
        javax.swing.BorderFactory.createCompoundBorder(
            javax.swing.BorderFactory.createTitledBorder("  Historial de movimientos"),
            javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5)
        )
    );
}
   // Llamado desde el constructor

private void stylePrimaryButton(javax.swing.JButton btn) {
    if (btn == null) return;

    java.awt.Color azul = new java.awt.Color(33, 150, 243);      // #2196F3
    java.awt.Color azulHover = new java.awt.Color(25, 118, 210); // #1976D2
    java.awt.Color texto = java.awt.Color.WHITE;

    btn.setBackground(azul);
    btn.setForeground(texto);
    btn.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 13));
    btn.setFocusPainted(false);
    btn.setBorderPainted(false);
    btn.setOpaque(true);
    btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

    // Bordecito redondeado
    btn.setBorder(new javax.swing.border.LineBorder(azulHover, 1, true));

    // Efecto hover
    addHoverEffect(btn, azul, azulHover);
}

private void styleDangerButton(javax.swing.JButton btn) {
    if (btn == null) return;

    java.awt.Color rojo = new java.awt.Color(244, 67, 54);       // #F44336
    java.awt.Color rojoHover = new java.awt.Color(211, 47, 47);  // #D32F2F
    java.awt.Color texto = java.awt.Color.WHITE;

    btn.setBackground(rojo);
    btn.setForeground(texto);
    btn.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 13));
    btn.setFocusPainted(false);
    btn.setBorderPainted(false);
    btn.setOpaque(true);
    btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    btn.setBorder(new javax.swing.border.LineBorder(rojoHover, 1, true));

    addHoverEffect(btn, rojo, rojoHover);
}
private void styleSecondaryButton(javax.swing.JButton btn) {
    if (btn == null) return;

    java.awt.Color gris = new java.awt.Color(224, 224, 224);     // #E0E0E0
    java.awt.Color grisHover = new java.awt.Color(189, 189, 189);// #BDBDBD
    java.awt.Color texto = new java.awt.Color(33, 33, 33);

    btn.setBackground(gris);
    btn.setForeground(texto);
    btn.setFont(new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 12));
    btn.setFocusPainted(false);
    btn.setBorderPainted(false);
    btn.setOpaque(true);
    btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    btn.setBorder(new javax.swing.border.LineBorder(grisHover, 1, true));

    addHoverEffect(btn, gris, grisHover);
}
private void addHoverEffect(final javax.swing.JButton btn,
                            final java.awt.Color normal,
                            final java.awt.Color hover) {

    btn.addMouseListener(new java.awt.event.MouseAdapter() {
        @Override
        public void mouseEntered(java.awt.event.MouseEvent e) {
            btn.setBackground(hover);
        }

        @Override
        public void mouseExited(java.awt.event.MouseEvent e) {
            btn.setBackground(normal);
        }
    });
}


private void estilizarBotones() {
    // Paleta
    java.awt.Color azul      = new java.awt.Color(0, 122, 255);
    java.awt.Color azulHover = new java.awt.Color(0, 153, 255);
    java.awt.Color rojo      = new java.awt.Color(230, 57, 70);
    java.awt.Color rojoHover = rojo.darker();

    // 👇 Ajusta estos nombres a los que tengas en tu formulario
    configurarBoton(btnGuardar,        azul, azulHover);
    configurarBoton(btnNuevoProducto,  azul, azulHover);
    configurarBoton(btnAgregarStock,   azul, azulHover);
    configurarBoton(btnRegistrarVenta, azul, azulHover);
    configurarBoton(btnEliminar,       rojo, rojoHover);
}

private void configurarBoton(javax.swing.JButton boton,
                             java.awt.Color colorNormal,
                             java.awt.Color colorHover) {

    // Sin bordes feos de Swing
    boton.setFocusPainted(false);
    boton.setBorderPainted(false);
    boton.setContentAreaFilled(false);
    boton.setOpaque(true);

    // Colores y tipografía
    boton.setBackground(colorNormal);
    boton.setForeground(java.awt.Color.WHITE);
    boton.setFont(
        boton.getFont().deriveFont(java.awt.Font.BOLD, 12f)
    );

    // Cursor de mano
    boton.setCursor(
        java.awt.Cursor.getPredefinedCursor(java.awt.Cursor.HAND_CURSOR)
    );

    // Hover
    boton.addMouseListener(new java.awt.event.MouseAdapter() {
        @Override
        public void mouseEntered(java.awt.event.MouseEvent e) {
            boton.setBackground(colorHover);
        }

        @Override
        public void mouseExited(java.awt.event.MouseEvent e) {
            boton.setBackground(colorNormal);
        }
    });
}
private void crearMenuAdmin() {
    JMenuBar barra = new JMenuBar();

    // Menú "Inventario"
    JMenu menuInventario = new JMenu("Inventario");
    JMenuItem itemNuevo = new JMenuItem("Nuevo producto");
    JMenuItem itemRefrescar = new JMenuItem("Actualizar lista");

    itemNuevo.addActionListener(e -> {
        // aquí abres tu formulario de nuevo producto o limpias campos
        btnNuevoProducto.doClick();   // si ya tienes ese botón
    });

    itemRefrescar.addActionListener(e -> {
        cargarProductos();
        configurarTablaHistorial();
    });

    menuInventario.add(itemNuevo);
    menuInventario.add(itemRefrescar);

    // Menú "Sesión"
    JMenu menuSesion = new JMenu("Sesión");
    JMenuItem itemCerrarSesion = new JMenuItem("Cerrar sesión");
    JMenuItem itemSalir = new JMenuItem("Salir");

    itemCerrarSesion.addActionListener(e -> {
        this.dispose();
        new acceso().setVisible(true);   // volver al login
    });

    itemSalir.addActionListener(e -> System.exit(0));

    menuSesion.add(itemCerrarSesion);
    menuSesion.add(itemSalir);

    // Menú "Ayuda"
    JMenu menuAyuda = new JMenu("Ayuda");
    JMenuItem itemAcerca = new JMenuItem("Acerca de...");
    itemAcerca.addActionListener(e -> {
        javax.swing.JOptionPane.showMessageDialog(this,
            "Minimarket Kathycita\nMódulo de Administración de Inventario",
            "Acerca de", javax.swing.JOptionPane.INFORMATION_MESSAGE);
    });
    menuAyuda.add(itemAcerca);

    // Añadir menús a la barra
    barra.add(menuInventario);
    barra.add(menuSesion);
    barra.add(menuAyuda);

    // Asignar la barra al frame
    setJMenuBar(barra);
}


private void refrescarListaProductos() {
    DefaultListModel<String> modelo = new DefaultListModel<>();
    for (Producto prod : listaProductos) {
        modelo.addElement(prod.getNombre());
    }
    lstProductos.setModel(modelo);
}











    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JdetallesProducto;
    private javax.swing.JButton btnAgregarStock;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnNuevoProducto;
    private javax.swing.JButton btnRegistrarVenta;
    private javax.swing.JCheckBox chkActivo;
    private javax.swing.JCheckBox chkDescontinuad;
    private javax.swing.JPanel chkDescontinuado;
    private javax.swing.JComboBox<String> cmbNombre;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JList<String> lstProductos;
    private javax.swing.JPanel panelHistorial;
    private javax.swing.JPanel panelMain;
    private javax.swing.JPanel panelProductos;
    private javax.swing.JTable tblHistorial;
    private javax.swing.JTextField txtAgregarStock;
    private javax.swing.JTextField txtBuscar;
    private javax.swing.JTextField txtCantidadStock;
    private javax.swing.JTextField txtPrecioUnitario;
    private javax.swing.JTextField txtRegistrarVenta;
    // End of variables declaration//GEN-END:variables


}// ← este es el cierre de la clase AdminInventarioFrame







