/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package capasPresentacion;

import Clases.Factura;
import Clases.Detalle;
import Clases.Producto;
import Clasesdao.FacturaDAO;
import Clasesdao.DetalleDAO;
import Clasesdao.ProductoDAO;
import java.awt.Color;
import java.awt.Font;
import java.math.BigDecimal;
import javax.swing.BorderFactory;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
import javax.swing.table.JTableHeader;

/**
 *
 * @author marci
 */
public class FacturaFrame extends javax.swing.JFrame {
    
    private int idFactura;
    private final FacturaDAO facturaDAO = new FacturaDAO();
    private final DetalleDAO detalleDAO = new DetalleDAO();
    private final ProductoDAO productoDAO = new ProductoDAO();
    private String nombreCliente;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FacturaFrame.class.getName());
    

    /**
     * Creates new form FacturaFrame
     */
    public FacturaFrame() {
        
    initComponents();
    setLocationRelativeTo(null);
     cargarLogo();
     personalizarFactura();
     personalizarTablaDetalle();
     estilizarFactura();
     
    }
    public FacturaFrame(int idFactura,String nombreCliente) {
    this(); 
    this.idFactura = idFactura;
     this.nombreCliente = nombreCliente;
    
    lblNombreClienteValor.setText(nombreCliente);

    // Configuramos el modelo de la tabla DETALLE
    javax.swing.table.DefaultTableModel modelo =
        new javax.swing.table.DefaultTableModel(
            new Object [][] {},
            new String [] { "DESCRIPCIÓN", "CANTIDAD", "PRECIO UNIT.", "TOTAL" }
        ) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false; // que no se puedan editar las celdas
            }
        };

    // Si tu tabla se llama jTable1:
    tblDetalle.setModel(modelo);
    // (si la renombraste a tblDetalle, cambia esa línea por tblDetalle.setModel(modelo);)

    cargarFactura();
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelHoja = new javax.swing.JPanel();
        lblTituloFactura = new javax.swing.JLabel();
        lblNombreTienda = new javax.swing.JLabel();
        lblTelefono = new javax.swing.JLabel();
        lblDireccion = new javax.swing.JLabel();
        lblCorreo = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lblNumeroFactura = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lblFechaFactura = new javax.swing.JLabel();
        tblDetalles = new javax.swing.JScrollPane();
        tblDetalle = new javax.swing.JTable();
        lblTextoTotal = new javax.swing.JLabel();
        lblTotalFactura = new javax.swing.JLabel();
        lblGracias = new javax.swing.JLabel();
        lblTextoSubtotal = new javax.swing.JLabel();
        lblTextoIGV = new javax.swing.JLabel();
        lblSubtotal = new javax.swing.JLabel();
        lblIGV = new javax.swing.JLabel();
        lblLogo = new javax.swing.JLabel();
        lblNombreClienteValor = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(232, 236, 245));

        panelHoja.setBackground(new java.awt.Color(255, 255, 255));
        panelHoja.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        panelHoja.setForeground(new java.awt.Color(255, 255, 255));

        lblTituloFactura.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        lblTituloFactura.setText("     FACTURA");

        lblNombreTienda.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblNombreTienda.setText("MINIMARKET KATHYCITA");

        lblTelefono.setText("975 796 578");

        lblDireccion.setText("Jr Otuzco 260 San felipe comas");

        lblCorreo.setText("kathycita@gmail.com");

        jLabel4.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        jLabel4.setText("Nombre del cliente");

        jLabel6.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel6.setText("N° FACTURA");

        jLabel7.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel7.setText("FECHA");

        tblDetalle.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblDetalle.setName("tblDetalle"); // NOI18N
        tblDetalles.setViewportView(tblDetalle);

        lblTextoTotal.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblTextoTotal.setText("TOTAL:");

        lblGracias.setBackground(new java.awt.Color(0, 204, 102));
        lblGracias.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblGracias.setForeground(new java.awt.Color(255, 255, 255));
        lblGracias.setText("¡Gracias por su compra!");
        lblGracias.setOpaque(true);

        lblTextoSubtotal.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblTextoSubtotal.setText("SUBTOTAL:");

        lblTextoIGV.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblTextoIGV.setText("IGV (18%):");

        lblLogo.setPreferredSize(new java.awt.Dimension(250, 150));

        javax.swing.GroupLayout panelHojaLayout = new javax.swing.GroupLayout(panelHoja);
        panelHoja.setLayout(panelHojaLayout);
        panelHojaLayout.setHorizontalGroup(
            panelHojaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelHojaLayout.createSequentialGroup()
                .addGroup(panelHojaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelHojaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblTituloFactura, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(panelHojaLayout.createSequentialGroup()
                        .addGroup(panelHojaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelHojaLayout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(lblNombreTienda))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelHojaLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(panelHojaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblNumeroFactura, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblTelefono, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblCorreo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblDireccion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(panelHojaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelHojaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblFechaFactura, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblNombreClienteValor, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(tblDetalles, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 567, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelHojaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelHojaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelHojaLayout.createSequentialGroup()
                        .addGroup(panelHojaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lblTextoIGV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblTextoSubtotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblTextoTotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(panelHojaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelHojaLayout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addComponent(lblTotalFactura, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelHojaLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblSubtotal, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelHojaLayout.createSequentialGroup()
                                .addGap(48, 48, 48)
                                .addComponent(lblIGV, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(48, 48, 48))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelHojaLayout.createSequentialGroup()
                        .addComponent(lblGracias, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(127, 127, 127))))
        );
        panelHojaLayout.setVerticalGroup(
            panelHojaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelHojaLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(panelHojaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTituloFactura, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelHojaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNombreTienda, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(panelHojaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNombreClienteValor, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblCorreo)
                .addGap(8, 8, 8)
                .addComponent(lblTelefono)
                .addGap(28, 28, 28)
                .addGroup(panelHojaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelHojaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelHojaLayout.createSequentialGroup()
                        .addComponent(lblNumeroFactura, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(tblDetalles, javax.swing.GroupLayout.PREFERRED_SIZE, 394, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblFechaFactura, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(62, 62, 62)
                .addGroup(panelHojaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelHojaLayout.createSequentialGroup()
                        .addComponent(lblTextoSubtotal, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(panelHojaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelHojaLayout.createSequentialGroup()
                                .addGroup(panelHojaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblTextoIGV, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblIGV, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblTextoTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblTotalFactura, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(lblSubtotal, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(68, 68, 68)
                .addComponent(lblGracias, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelHoja, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelHoja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FacturaFrame().setVisible(true));
    }
    
    public void cargarFactura(){
         // 1) Obtener la cabecera de la factura
    Factura f = facturaDAO.buscarPorId(idFactura);
    if (f == null) {
        javax.swing.JOptionPane.showMessageDialog(
                this,
                "No se encontró la factura N° " + idFactura,
                "Error",
                javax.swing.JOptionPane.ERROR_MESSAGE
        );
        dispose();
        return;
    }

    // Cabecera
    lblNumeroFactura.setText(String.valueOf(f.getIdfactura()));
    lblFechaFactura.setText(f.getFechaFactura().toString());
    // lblNombreCliente normalmente ya se setea en el constructor con this.nombreCliente

    // 2) Limpiar modelo de la tabla
    javax.swing.table.DefaultTableModel modelo =
            (javax.swing.table.DefaultTableModel) tblDetalle.getModel();
    modelo.setRowCount(0);

    // 3) Rellenar detalles
    java.math.BigDecimal total = java.math.BigDecimal.ZERO;

    for (Detalle d : detalleDAO.listarPorFactura(idFactura)) {
        Producto p = productoDAO.buscarPorId(d.getIdproducto());
        String nombreProd = (p != null)
                ? p.getNombre()
                : "Producto ID " + d.getIdproducto();

        java.math.BigDecimal subtotal =
                d.getPrecioUnitario().multiply(
                        new java.math.BigDecimal(d.getCantidad())
                );

        modelo.addRow(new Object[]{
                nombreProd,
                d.getCantidad(),
                "S/ " + d.getPrecioUnitario(),
                "S/ " + subtotal
        });

        total = total.add(subtotal);
    }

    // 4) Calcular subtotal + IGV (18 %) a partir del total
    java.math.BigDecimal cien    = new java.math.BigDecimal("100");
    java.math.BigDecimal igvPorc = new java.math.BigDecimal("18");

    // subtotal = total / 1.18  (pero hecho como total * 100 / 118)
    java.math.BigDecimal divisor = cien.add(igvPorc); // 118
    java.math.BigDecimal subtotal =
            total.multiply(cien)
                 .divide(divisor, 2, java.math.RoundingMode.HALF_UP);

    java.math.BigDecimal igv = total.subtract(subtotal);

    lblSubtotal.setText("S/ " + subtotal);
    lblIGV.setText("S/ " + igv);
    lblTotalFactura.setText("S/ " + total);
    }
    
    private void cargarLogo() {
     java.net.URL url = getClass().getResource("/imagenes/tienda.png");
    if (url == null) {
        // Debug para saber si el problema es la ruta
        javax.swing.JOptionPane.showMessageDialog(
                this,
                "No se encontró la imagen /imagenes/tienda.png",
                "Error logo",
                javax.swing.JOptionPane.ERROR_MESSAGE
        );
        return;
    }

    // 2. Crear el ImageIcon original
    javax.swing.ImageIcon iconoOriginal = new javax.swing.ImageIcon(url);

    // 3. Escalar a un tamaño fijo (ajusta 180x90 si quieres otro)
    int ancho = 250;
    int alto  = 150;

    java.awt.Image imgEscalada = iconoOriginal.getImage()
            .getScaledInstance(ancho, alto, java.awt.Image.SCALE_SMOOTH);

    // 4. Asignar al label
    lblLogo.setIcon(new javax.swing.ImageIcon(imgEscalada));
    lblLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    lblLogo.setVerticalAlignment(javax.swing.SwingConstants.CENTER);
}
    
    private void personalizarFactura() {
    // Fondo general gris clarito
    getContentPane().setBackground(new java.awt.Color(235, 238, 244)); // #EBEEF4

    // Panel “hoja” en blanco con margen
    panelHoja.setBackground(java.awt.Color.WHITE);
    panelHoja.setBorder(
        javax.swing.BorderFactory.createCompoundBorder(
            javax.swing.BorderFactory.createEmptyBorder(15, 20, 15, 20), // margen
            javax.swing.BorderFactory.createLineBorder(new java.awt.Color(220, 220, 220))
        )
    );
    
    // Título FACTURA más elegante
lblTituloFactura.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 28));

// Nombre de la tienda en negrita
lblNombreTienda.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 14));

// Textos pequeños del encabezado
lblDireccion.setFont(new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 12));
lblCorreo.setFont(new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 12));
lblTelefono.setFont(new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 12));

// Etiquetas de totales
lblTextoSubtotal.setFont(new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 13));
lblTextoIGV.setFont(new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 13));
lblTextoTotal.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 14));

// Valores de totales
lblSubtotal.setFont(new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 13));
lblIGV.setFont(new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 13));
lblTotalFactura.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 14));
lblTotalFactura.setForeground(new java.awt.Color(30, 132, 73)); // verdoso

// Cabecera de la tabla
javax.swing.table.JTableHeader header = tblDetalle.getTableHeader();
header.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 12));
header.setReorderingAllowed(false); // que no muevan columnas
header.setResizingAllowed(false);

// Cuerpo de la tabla
tblDetalle.setFont(new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 12));
tblDetalle.setRowHeight(22);

// Color de líneas de la tabla
tblDetalle.setGridColor(new java.awt.Color(220, 220, 220));

// Alinear columnas numéricas al centro/derecha
javax.swing.table.DefaultTableCellRenderer center = new javax.swing.table.DefaultTableCellRenderer();
center.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

javax.swing.table.DefaultTableCellRenderer right = new javax.swing.table.DefaultTableCellRenderer();
right.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

tblDetalle.getColumnModel().getColumn(1).setCellRenderer(center); // CANTIDAD
tblDetalle.getColumnModel().getColumn(2).setCellRenderer(right);  // PRECIO UNIT.
tblDetalle.getColumnModel().getColumn(3).setCellRenderer(right);  // TOTAL

lblGracias.setOpaque(true);
lblGracias.setBackground(new java.awt.Color(0, 177, 89)); // verde
lblGracias.setForeground(java.awt.Color.WHITE);
lblGracias.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
lblGracias.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 16));
lblGracias.setBorder(
    javax.swing.BorderFactory.createEmptyBorder(8, 20, 8, 20)
);


}
    
    private void personalizarTablaDetalle() {
    // Cabecera de la tabla
    javax.swing.table.JTableHeader header = tblDetalle.getTableHeader();
    header.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 12));
    header.setOpaque(true);
    header.setBackground(new java.awt.Color(245, 245, 245));  // gris claro
    header.setForeground(new java.awt.Color(60, 60, 60));     // texto gris oscuro
    header.setReorderingAllowed(false);  // que no muevan columnas

    // Cuerpo de la tabla
    tblDetalle.setFont(new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 12));
    tblDetalle.setRowHeight(24);
    tblDetalle.setGridColor(new java.awt.Color(230, 230, 230));
    tblDetalle.setShowHorizontalLines(true);
    tblDetalle.setShowVerticalLines(false);

    // Renderer para filas tipo "zebra" + alineación numérica
    javax.swing.table.DefaultTableCellRenderer renderer =
        new javax.swing.table.DefaultTableCellRenderer() {

        @Override
        public java.awt.Component getTableCellRendererComponent(
                javax.swing.JTable table, Object value,
                boolean isSelected, boolean hasFocus,
                int row, int column) {

            java.awt.Component c = super.getTableCellRendererComponent(
                    table, value, isSelected, hasFocus, row, column);

            // Colores de fondo (zebra)
            if (!isSelected) {
                if (row % 2 == 0) {
                    c.setBackground(java.awt.Color.WHITE);
                } else {
                    c.setBackground(new java.awt.Color(248, 250, 252)); // gris muy suave
                }
            }

            // Alineación: 
            // col 0 = DESCRIPCIÓN (izquierda)
            // col 1 = CANTIDAD (centro)
            // col 2 = PRECIO UNIT. (derecha)
            // col 3 = TOTAL (derecha)
            if (column == 1) {
                setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            } else if (column == 2 || column == 3) {
                setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
            } else {
                setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
            }

            return c;
        }
    };

    // Aplicar el renderer a todas las columnas
    for (int i = 0; i < tblDetalle.getColumnCount(); i++) {
        tblDetalle.getColumnModel().getColumn(i).setCellRenderer(renderer);
    }
}
    private void estilizarFactura() {
    // 1) Panel principal tipo hoja A4
    panelHoja.setBackground(Color.WHITE);
    panelHoja.setBorder(
        BorderFactory.createEmptyBorder(20, 40, 20, 40)  // márgenes de la "hoja"
    );

    // 2) Título FACTURA
    lblTituloFactura.setText("FACTURA");
    lblTituloFactura.setFont(new Font("Segoe UI", Font.BOLD, 26));
    lblTituloFactura.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

    // 3) Nombre de la empresa
    lblNombreTienda.setFont(new Font("Segoe UI", Font.BOLD, 12));

   

    // 5) Tabla de detalle
    JTableHeader header = tblDetalle.getTableHeader();
    header.setBackground(new Color(0, 102, 204));   // azul
    header.setForeground(Color.WHITE);              // letras blancas
    header.setFont(new Font("Segoe UI", Font.BOLD, 11));

    tblDetalle.setRowHeight(22);
    tblDetalle.setShowGrid(true);
    tblDetalle.setGridColor(new Color(220, 220, 220));

    

    lblSubtotal.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
    lblTextoIGV.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
    lblTextoTotal.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

    lblTextoTotal.setFont(new Font("Segoe UI", Font.BOLD, 13));
    lblTextoTotal.setForeground(new Color(0, 128, 0));   // verde

    
}





    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel lblCorreo;
    private javax.swing.JLabel lblDireccion;
    private javax.swing.JLabel lblFechaFactura;
    private javax.swing.JLabel lblGracias;
    private javax.swing.JLabel lblIGV;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblNombreClienteValor;
    private javax.swing.JLabel lblNombreTienda;
    private javax.swing.JLabel lblNumeroFactura;
    private javax.swing.JLabel lblSubtotal;
    private javax.swing.JLabel lblTelefono;
    private javax.swing.JLabel lblTextoIGV;
    private javax.swing.JLabel lblTextoSubtotal;
    private javax.swing.JLabel lblTextoTotal;
    private javax.swing.JLabel lblTituloFactura;
    private javax.swing.JLabel lblTotalFactura;
    private javax.swing.JPanel panelHoja;
    private javax.swing.JTable tblDetalle;
    private javax.swing.JScrollPane tblDetalles;
    // End of variables declaration//GEN-END:variables
}
