/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package capasPresentacion;

import Clases.Producto;
import Clasesdao.ProductoDAO;
import java.util.List;
import Clases.Factura;
import Clases.Detalle;
import Clasesdao.FacturaDAO;
import Clasesdao.DetalleDAO;
import Clases.Usuario; 
import java.awt.Color;
import javax.swing.JMenuBar;
import javax.swing.JMenu;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;


/**
 *
 * @author marci
 */
public class usuarioCompra2 extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(usuarioCompra2.class.getName());
    private ProductoDAO productoDAO;
    private java.util.List<Producto> listaProductosUsuario;
    private Usuario usuarioActual;
    private String nombreCliente;
    



    /**
     * Creates new form usuarioCompra2
     */
    public usuarioCompra2(String nombreCliente) {
        initComponents();
        
        setLocationRelativeTo(null);
        this.nombreCliente = nombreCliente;
        personalizarUICompra();
        productoDAO = new ProductoDAO();
        configurarTablaCarrito();
        cargarProductosUsuario();
        crearMenuUsuario();
        
        Color fondo = new Color(238, 247, 255); // azul muy clarito, cámbialo si quieres

    // Fondo del frame
    getContentPane().setBackground(fondo);

    // Fondos de los paneles principales
    panelIzquierda.setBackground(fondo);
    panelDerecha.setBackground(fondo);
        
        
        tblCarrito.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        
         lstProductosUsuario.addListSelectionListener(e -> {
        if (e.getValueIsAdjusting()) return;

        int idx = lstProductosUsuario.getSelectedIndex();
        if (idx >= 0 && idx < listaProductosUsuario.size()) {
            Producto p = listaProductosUsuario.get(idx);

            // si quieres mostrar info en algún label/textfield extra
            // por ahora, solo dejamos la selección
        }
    });
    }
    public usuarioCompra2() {
    this("Cliente demo");
}

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        panelIzquierda = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtBuscarUsuario = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtCantidadComprar = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstProductosUsuario = new javax.swing.JList<>();
        btnAgregarCarrito = new javax.swing.JButton();
        panelDerecha = new javax.swing.JPanel();
        jScrollPaneCarrito = new javax.swing.JScrollPane();
        tblCarrito = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        lblTotalPagar = new javax.swing.JLabel();
        btnFinalizarCompra = new javax.swing.JButton();
        btnVaciarCarrito = new javax.swing.JButton();
        btnEliminarProducto = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(153, 204, 255));

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblTitulo.setText("COMPRA DE PRODUCTOS");

        panelIzquierda.setBackground(new java.awt.Color(255, 255, 255));
        panelIzquierda.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "AÑADIR PRODUCTO", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 14))); // NOI18N
        panelIzquierda.setForeground(new java.awt.Color(0, 204, 255));

        jLabel1.setText("Buscar");

        txtBuscarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscarUsuarioActionPerformed(evt);
            }
        });

        jLabel2.setText("Cantidad");

        lstProductosUsuario.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(lstProductosUsuario);

        btnAgregarCarrito.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnAgregarCarrito.setText("Añadir al carrito");
        btnAgregarCarrito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarCarritoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelIzquierdaLayout = new javax.swing.GroupLayout(panelIzquierda);
        panelIzquierda.setLayout(panelIzquierdaLayout);
        panelIzquierdaLayout.setHorizontalGroup(
            panelIzquierdaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelIzquierdaLayout.createSequentialGroup()
                .addGroup(panelIzquierdaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelIzquierdaLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(panelIzquierdaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtBuscarUsuario)
                            .addComponent(txtCantidadComprar, javax.swing.GroupLayout.DEFAULT_SIZE, 229, Short.MAX_VALUE)))
                    .addGroup(panelIzquierdaLayout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(btnAgregarCarrito, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        panelIzquierdaLayout.setVerticalGroup(
            panelIzquierdaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelIzquierdaLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtBuscarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtCantidadComprar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(btnAgregarCarrito, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(66, Short.MAX_VALUE))
        );

        panelDerecha.setBackground(new java.awt.Color(255, 255, 255));
        panelDerecha.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "TU CARRITO", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 14))); // NOI18N
        panelDerecha.setForeground(new java.awt.Color(0, 204, 255));

        tblCarrito.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Producto", "Cantidad", "Precio Unit.", "Subtotal"
            }
        ));
        jScrollPaneCarrito.setViewportView(tblCarrito);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("TOTAL A PAGAR");

        lblTotalPagar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblTotalPagar.setText("       S/ 0.00");

        btnFinalizarCompra.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnFinalizarCompra.setText("FINALIZAR COMPRA");
        btnFinalizarCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFinalizarCompraActionPerformed(evt);
            }
        });

        btnVaciarCarrito.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnVaciarCarrito.setText("Vaciar carrito");
        btnVaciarCarrito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVaciarCarritoActionPerformed(evt);
            }
        });

        btnEliminarProducto.setText("ELIMINAR PRODUCTO");
        btnEliminarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarProductoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelDerechaLayout = new javax.swing.GroupLayout(panelDerecha);
        panelDerecha.setLayout(panelDerechaLayout);
        panelDerechaLayout.setHorizontalGroup(
            panelDerechaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDerechaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelDerechaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelDerechaLayout.createSequentialGroup()
                        .addComponent(jScrollPaneCarrito, javax.swing.GroupLayout.DEFAULT_SIZE, 485, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelDerechaLayout.createSequentialGroup()
                        .addGroup(panelDerechaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnEliminarProducto, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE)
                            .addComponent(btnVaciarCarrito, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(panelDerechaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTotalPagar, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(11, 11, 11))))
            .addGroup(panelDerechaLayout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addComponent(btnFinalizarCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        panelDerechaLayout.setVerticalGroup(
            panelDerechaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDerechaLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jScrollPaneCarrito, javax.swing.GroupLayout.PREFERRED_SIZE, 518, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelDerechaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnEliminarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelDerechaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTotalPagar)
                    .addComponent(btnVaciarCarrito, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(btnFinalizarCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(panelIzquierda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(panelDerecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblTitulo)
                .addGap(276, 276, 276))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelIzquierda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelDerecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(45, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnFinalizarCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFinalizarCompraActionPerformed
       // 0) Modelo del carrito
    javax.swing.table.DefaultTableModel modelo =
            (javax.swing.table.DefaultTableModel) tblCarrito.getModel();

    int filas = modelo.getRowCount();
    if (filas == 0) {
        javax.swing.JOptionPane.showMessageDialog(
                this,
                "El carrito está vacío.",
                "Aviso",
                javax.swing.JOptionPane.WARNING_MESSAGE
        );
        return;
    }
    

    // ----- 1) Armar filas de la tabla en HTML (para el cuadro de confirmación) -----
    StringBuilder filasHtml = new StringBuilder();

    for (int i = 0; i < filas; i++) {
        String nombreProd  = modelo.getValueAt(i, 0).toString();
        String cantStr     = modelo.getValueAt(i, 1).toString();
        String precioStr   = modelo.getValueAt(i, 2).toString();
        String subtotalStr = modelo.getValueAt(i, 3).toString();

        filasHtml.append("<tr>")
                .append("<td style='padding:4px 8px;'>").append(nombreProd).append("</td>")
                .append("<td style='padding:4px 8px; text-align:center;'>").append(cantStr).append("</td>")
                .append("<td style='padding:4px 8px; text-align:right;'>S/ ").append(precioStr).append("</td>")
                .append("<td style='padding:4px 8px; text-align:right;'>S/ ").append(subtotalStr).append("</td>")
                .append("</tr>");
    }

    // ----- 2) Armar el HTML completo -----
    String detalleHtml =
            "<html>" +
                    "<body style='font-family:Segoe UI, sans-serif; font-size:11px; background:#f5f7fb;'>" +
                    "<h3 style='margin:0 0 8px 0;'>Detalle de la compra</h3>" +
                    "<table style='border-collapse:collapse;'>" +
                    "<tr style='background:#dde7ff;'>" +
                    "<th style='padding:4px 8px; text-align:left;'>Producto</th>" +
                    "<th style='padding:4px 8px; text-align:center;'>Cant.</th>" +
                    "<th style='padding:4px 8px; text-align:right;'>P. Unit</th>" +
                    "<th style='padding:4px 8px; text-align:right;'>Subtotal</th>" +
                    "</tr>" +
                    filasHtml +
                    "</table>" +
                    "<p style='margin-top:10px; font-weight:bold; text-align:right;'>" +
                    "TOTAL A PAGAR: " + lblTotalPagar.getText() +
                    "</p>" +
                    "</body>" +
                    "</html>";

    java.awt.Color fondo = new java.awt.Color(245, 247, 251); // #f5f7fb
    javax.swing.UIManager.put("OptionPane.background", fondo);
    javax.swing.UIManager.put("Panel.background", fondo);

    // ----- 3) Cuadro de confirmación “bonito” -----
    int opcion = javax.swing.JOptionPane.showConfirmDialog(
            this,
            detalleHtml,
            "Confirmar compra",
            javax.swing.JOptionPane.YES_NO_OPTION,
            javax.swing.JOptionPane.PLAIN_MESSAGE
    );

    if (opcion != javax.swing.JOptionPane.YES_OPTION) {
        // Usuario canceló
        return;
    }

    // ----- 4) Crear la factura (cabecera) -----
    FacturaDAO facturaDAO = new FacturaDAO();
    int idFactura = facturaDAO.crearFacturaHoy();   // ESTE método debe insertar en dbo.factura y devolver el id

    if (idFactura == -1) {
        javax.swing.JOptionPane.showMessageDialog(
                this,
                "No se pudo crear la factura en la base de datos.",
                "Error",
                javax.swing.JOptionPane.ERROR_MESSAGE
        );
        return;
    }

    // ----- 5) Insertar detalles + descontar stock -----
    DetalleDAO detalleDAO = new DetalleDAO();

    for (int i = 0; i < filas; i++) {
        String nombreProd = modelo.getValueAt(i, 0).toString();
        int cantidad = Integer.parseInt(modelo.getValueAt(i, 1).toString());
        java.math.BigDecimal precioUnit =
                new java.math.BigDecimal(modelo.getValueAt(i, 2).toString());

        // Buscar el producto por nombre (usa tu método de ayuda)
        Producto p = buscarProductoPorNombre(nombreProd);
        if (p == null) {
            javax.swing.JOptionPane.showMessageDialog(
                    this,
                    "No se encontró el producto: " + nombreProd,
                    "Error",
                    javax.swing.JOptionPane.ERROR_MESSAGE
            );
            continue; // o return; tú decides
        }

        // Crear el detalle
        Detalle d = new Detalle();
        // Si tu columna iddetalle es IDENTITY, puedes dejarlo en 0 o no usarlo en el INSERT 
        d.setIdfactura(idFactura);
        d.setIdproducto(p.getIdproducto());
        d.setCantidad(cantidad);
        d.setPrecioUnitario(precioUnit);

        boolean okDet = detalleDAO.insertar(d);
        if (!okDet) {
            javax.swing.JOptionPane.showMessageDialog(
                    this,
                    "No se pudo registrar el detalle de: " + nombreProd,
                    "Error",
                    javax.swing.JOptionPane.ERROR_MESSAGE
            );
        } else {
            // Descontar stock en BD (ajusta al método que tengas en tu ProductoDAO)
            int stockNuevo = p.getStock() - cantidad;
            if (stockNuevo < 0) {
                stockNuevo = 0;
            }
            p.setStock(stockNuevo);
            productoDAO.actualizar(p);   // o actualizarProducto(p) / actualizarStock(...), según tu DAO
        }
    }

    // ----- 6) Mensaje de éxito -----
    javax.swing.JOptionPane.showMessageDialog(
            this,
            "Compra registrada correctamente.\nFactura N°: " + idFactura,
            "Éxito",
            javax.swing.JOptionPane.INFORMATION_MESSAGE
    );

    // ----- 7) Abrir la factura 🧾 -----
    String nombreCliente = this.nombreCliente;
    if (nombreCliente == null || nombreCliente.isBlank()) {
        nombreCliente = "Cliente";
    }

    FacturaFrame f = new FacturaFrame(idFactura, nombreCliente);
    f.setVisible(true);

    // ----- 8) Limpiar carrito y refrescar lista de productos -----
    modelo.setRowCount(0);
    lblTotalPagar.setText("S/ 0.00");
    cargarProductosUsuario();

    }//GEN-LAST:event_btnFinalizarCompraActionPerformed

    private void btnAgregarCarritoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarCarritoActionPerformed
        int idx = lstProductosUsuario.getSelectedIndex();
    if (idx < 0 || idx >= listaProductosUsuario.size()) {
        javax.swing.JOptionPane.showMessageDialog(this,
                "Selecciona un producto de la lista.",
                "Aviso",
                javax.swing.JOptionPane.WARNING_MESSAGE);
        return;
    }

    String txtCant = txtCantidadComprar.getText().trim();
    if (txtCant.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this,
                "Ingresa la cantidad a comprar.",
                "Aviso",
                javax.swing.JOptionPane.WARNING_MESSAGE);
        return;
    }

    int cantidad;
    try {
        cantidad = Integer.parseInt(txtCant);
        if (cantidad <= 0) throw new NumberFormatException();
    } catch (NumberFormatException ex) {
        javax.swing.JOptionPane.showMessageDialog(this,
                "La cantidad debe ser un entero mayor que 0.",
                "Cantidad inválida",
                javax.swing.JOptionPane.ERROR_MESSAGE);
        return;
    }

    Producto p = listaProductosUsuario.get(idx);

    if (cantidad > p.getStock()) {
        javax.swing.JOptionPane.showMessageDialog(this,
                "No hay stock suficiente. Stock disponible: " + p.getStock(),
                "Stock insuficiente",
                javax.swing.JOptionPane.WARNING_MESSAGE);
        return;
    }

    java.math.BigDecimal precio = p.getPrecioProducto();
    java.math.BigDecimal subtotal = precio.multiply(java.math.BigDecimal.valueOf(cantidad));

    javax.swing.table.DefaultTableModel modelo =
            (javax.swing.table.DefaultTableModel) tblCarrito.getModel();

    modelo.addRow(new Object[]{
            p.getNombre(),
            cantidad,
            precio,
            subtotal
    });

    actualizarTotalCarrito();
    txtCantidadComprar.setText("");
    }//GEN-LAST:event_btnAgregarCarritoActionPerformed

    private void btnVaciarCarritoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVaciarCarritoActionPerformed
         javax.swing.table.DefaultTableModel modelo =
            (javax.swing.table.DefaultTableModel) tblCarrito.getModel();

    modelo.setRowCount(0); // borra todas las filas
    lblTotalPagar.setText("S/ 0.00");
    }//GEN-LAST:event_btnVaciarCarritoActionPerformed

    private void txtBuscarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscarUsuarioActionPerformed
        String texto = txtBuscarUsuario.getText().trim().toLowerCase();

    if (texto.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(
                this,
                "Escribe algo para buscar.",
                "Buscar",
                javax.swing.JOptionPane.WARNING_MESSAGE
        );
        return;
    }

    int encontrado = -1;

    // Buscar en listaProductosUsuario por nombre
    for (int i = 0; i < listaProductosUsuario.size(); i++) {
        Producto p = listaProductosUsuario.get(i);
        if (p.getNombre().toLowerCase().contains(texto)) {
            encontrado = i;
            break;
        }
    }

    if (encontrado == -1) {
        javax.swing.JOptionPane.showMessageDialog(
                this,
                "No se encontró ningún producto con: " + texto,
                "Sin resultados",
                javax.swing.JOptionPane.INFORMATION_MESSAGE
        );
    } else {
        // Seleccionar en la lista y mostrarlo
        lstProductosUsuario.setSelectedIndex(encontrado);
        lstProductosUsuario.ensureIndexIsVisible(encontrado);

        // opcional: limpiar el texto de búsqueda
        // txtBuscarUsuario.setText("");
    }
    }//GEN-LAST:event_txtBuscarUsuarioActionPerformed

    private void btnEliminarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarProductoActionPerformed
         int fila = tblCarrito.getSelectedRow();

    if (fila == -1) {
        javax.swing.JOptionPane.showMessageDialog(
                this,
                "Selecciona un producto del carrito para eliminar.",
                "Sin selección",
                javax.swing.JOptionPane.WARNING_MESSAGE
        );
        return;
    }

    javax.swing.table.DefaultTableModel modelo =
            (javax.swing.table.DefaultTableModel) tblCarrito.getModel();

    modelo.removeRow(fila);       // elimina solo esa fila
    actualizarTotalCarrito();     // recalcula el total
    }//GEN-LAST:event_btnEliminarProductoActionPerformed

    private void configurarTablaCarrito() {
    javax.swing.table.DefaultTableModel modelo = new javax.swing.table.DefaultTableModel(
            new Object[]{"Producto", "Cantidad", "Precio Unit.", "Subtotal"}, 0
    ) {
        @Override
        public boolean isCellEditable(int row, int column) {
            return false; // que el usuario no edite directo la tabla
        }
    };

    tblCarrito.setModel(modelo);
}
    
    private void cargarProductosUsuario() {
    listaProductosUsuario = productoDAO.listarParaUsuario();

    javax.swing.DefaultListModel<String> modelo = new javax.swing.DefaultListModel<>();

    for (Producto p : listaProductosUsuario) {
        String linea =
            "<html>" +
                p.getNombre() + "<br>" +
                "<span style='font-size:10px; color:gray;'>S/ " + p.getPrecioProducto() + "</span>" +
            "</html>";

        modelo.addElement(linea);
    }

    lstProductosUsuario.setModel(modelo);
}
    
    private void actualizarTotalCarrito() {
    javax.swing.table.DefaultTableModel modelo =
            (javax.swing.table.DefaultTableModel) tblCarrito.getModel();

    java.math.BigDecimal total = java.math.BigDecimal.ZERO;

    for (int i = 0; i < modelo.getRowCount(); i++) {
        Object val = modelo.getValueAt(i, 3); // columna Subtotal
        if (val instanceof java.math.BigDecimal) {
            total = total.add((java.math.BigDecimal) val);
        } else if (val != null) {
            total = total.add(new java.math.BigDecimal(val.toString()));
        }
    }

    lblTotalPagar.setText("S/ " + total.toString());
}
    
    private Producto buscarProductoPorNombre(String nombre) {
    for (Producto p : listaProductosUsuario) {
        if (p.getNombre().equals(nombre)) {
            return p;
        }
    }
    return null;
}
   private void personalizarUICompra() {
    // Colores base (puedes cambiarlos a tu gusto)
    java.awt.Color azulSuave   = new java.awt.Color(222, 239, 255);
    java.awt.Color azulBoton   = new java.awt.Color(0, 153, 255);
    java.awt.Color azulBoton2  = new java.awt.Color(0, 102, 204);
    java.awt.Color rojoBoton   = new java.awt.Color(230, 76, 60);
    java.awt.Color textoOscuro = new java.awt.Color(40, 40, 40);

    
    // 2) Título principal: "COMPRA DE PRODUCTOS"
    lblTitulo.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 24));
    lblTitulo.setForeground(textoOscuro);

    

    lblTotalPagar.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 16));
    lblTotalPagar.setForeground(textoOscuro);

    lblTotalPagar.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 18));
    lblTotalPagar.setForeground(new java.awt.Color(0, 120, 0)); // verde para el total

    // 4) Labels de texto (Buscar, Cantidad, etc.)
    java.awt.Font labelFont = new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 13);
    jLabel1.setFont(labelFont);
    jLabel2.setFont(labelFont);

    // 5) Campos de texto
    jLabel1.setFont(new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 13));
    jLabel2.setFont(new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 13));

    // 6) Lista de productos (lstProductos)
    lstProductosUsuario.setFont(new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 13));
    lstProductosUsuario.setSelectionBackground(new java.awt.Color(51, 153, 255));
    lstProductosUsuario.setSelectionForeground(java.awt.Color.WHITE);

    // 7) Tabla del carrito (tblCarrito)
    tblCarrito.setFont(new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 13));
    tblCarrito.setRowHeight(24);
    tblCarrito.setShowGrid(true);
    tblCarrito.setGridColor(new java.awt.Color(230, 230, 230));
    tblCarrito.setSelectionBackground(new java.awt.Color(204, 230, 255));
    tblCarrito.setSelectionForeground(textoOscuro);

    javax.swing.table.JTableHeader header = tblCarrito.getTableHeader();
    header.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 13));
    header.setBackground(new java.awt.Color(0, 120, 215));
    header.setForeground(java.awt.Color.BLACK);
    header.setReorderingAllowed(false);

    // 8) Botones: estilo "glass"
    estilizarBotonGlass(btnAgregarCarrito, azulBoton, azulBoton2);
    estilizarBotonGlass(btnEliminarProducto, new java.awt.Color(255, 140, 0), new java.awt.Color(230, 120, 0));
    estilizarBotonGlass(btnVaciarCarrito, new java.awt.Color(128, 128, 128), new java.awt.Color(90, 90, 90));
    estilizarBotonGlass(btnFinalizarCompra, nuevoAzulFuerte(), nuevoAzulFuerte2());
}
   
   // Pequeño helper para crear botones tipo "glass"
private void estilizarBotonGlass(javax.swing.JButton boton, java.awt.Color c1, java.awt.Color c2) {
    boton.setFocusPainted(false);
    boton.setBorderPainted(false);
    boton.setForeground(java.awt.Color.WHITE);
    boton.setFont(new java.awt.Font("Segoe UI Semibold", java.awt.Font.PLAIN, 13));
    boton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    boton.setContentAreaFilled(false);

    boton.setBorder(javax.swing.BorderFactory.createEmptyBorder(8, 18, 8, 18));

    boton.setUI(new javax.swing.plaf.basic.BasicButtonUI() {
        @Override
        public void paint(java.awt.Graphics g, javax.swing.JComponent c) {
            java.awt.Graphics2D g2 = (java.awt.Graphics2D) g.create();
            g2.setRenderingHint(java.awt.RenderingHints.KEY_ANTIALIASING,
                                java.awt.RenderingHints.VALUE_ANTIALIAS_ON);

            int w = c.getWidth();
            int h = c.getHeight();

            // Fondo degradado
            java.awt.GradientPaint gp = new java.awt.GradientPaint(
                    0, 0, c1,
                    0, h, c2
            );
            g2.setPaint(gp);
            g2.fillRoundRect(0, 0, w, h, 18, 18);

            // Borde suave
            g2.setColor(new java.awt.Color(255, 255, 255, 70));
            g2.drawRoundRect(0, 0, w - 1, h - 1, 18, 18);

            // Texto centrado
            javax.swing.AbstractButton b = (javax.swing.AbstractButton) c;
            java.awt.FontMetrics fm = g2.getFontMetrics();
            java.awt.Rectangle r = new java.awt.Rectangle(0, 0, w, h);
            String text = b.getText();

            int textX = (w - fm.stringWidth(text)) / 2;
            int textY = (h + fm.getAscent() - fm.getDescent()) / 2;
            g2.setColor(java.awt.Color.WHITE);
            g2.drawString(text, textX, textY);

            g2.dispose();
        }
    });
}

// Opcional: colores específicos para el botón de "FINALIZAR COMPRA"
private java.awt.Color nuevoAzulFuerte()  { return new java.awt.Color(0, 122, 204); }
private java.awt.Color nuevoAzulFuerte2() { return new java.awt.Color(0, 90, 160); }



    private void crearMenuUsuario() {
    // ───── Barra de menú ─────
    JMenuBar barra = new JMenuBar();

    // ================== MENÚ CARRITO ==================
    JMenu menuCarrito = new JMenu("Carrito");

    JMenuItem itemAgregar = new JMenuItem("Añadir producto seleccionado");
    itemAgregar.addActionListener(e -> {
        // Simulamos click al botón de agregar
        if (btnAgregarCarrito != null) {
            btnAgregarCarrito.doClick();
        }
    });

    JMenuItem itemEliminar = new JMenuItem("Eliminar producto del carrito");
    itemEliminar.addActionListener(e -> {
        if (btnEliminarProducto != null) {
            btnEliminarProducto.doClick();
        }
    });

    JMenuItem itemVaciar = new JMenuItem("Vaciar carrito");
    itemVaciar.addActionListener(e -> {
        if (btnVaciarCarrito != null) {
            btnVaciarCarrito.doClick();
        }
    });

    JMenuItem itemFinalizar = new JMenuItem("Finalizar compra");
    itemFinalizar.addActionListener(e -> {
        if (btnFinalizarCompra != null) {
            btnFinalizarCompra.doClick();
        }
    });

    menuCarrito.add(itemAgregar);
    menuCarrito.add(itemEliminar);
    menuCarrito.addSeparator();
    menuCarrito.add(itemVaciar);
    menuCarrito.add(itemFinalizar);

    // ================== MENÚ SESIÓN ==================
    JMenu menuSesion = new JMenu("Sesión");

    JMenuItem itemCerrarSesion = new JMenuItem("Cerrar sesión");
    itemCerrarSesion.addActionListener(e -> {
        int resp = JOptionPane.showConfirmDialog(
                this,
                "¿Deseas cerrar sesión y volver al login?",
                "Cerrar sesión",
                JOptionPane.YES_NO_OPTION
        );
        if (resp == JOptionPane.YES_OPTION) {
            this.dispose();
            new acceso().setVisible(true); // vuelve a tu login
        }
    });

    JMenuItem itemSalir = new JMenuItem("Salir de la aplicación");
    itemSalir.addActionListener(e -> {
        int resp = JOptionPane.showConfirmDialog(
                this,
                "¿Seguro que deseas salir?",
                "Salir",
                JOptionPane.YES_NO_OPTION
        );
        if (resp == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    });

    menuSesion.add(itemCerrarSesion);
    menuSesion.add(itemSalir);

    // ================== MENÚ AYUDA ==================
    JMenu menuAyuda = new JMenu("Ayuda");

    JMenuItem itemAcerca = new JMenuItem("Acerca de...");
    itemAcerca.addActionListener(e -> {
        JOptionPane.showMessageDialog(
                this,
                "Minimarket Kathycita\nMódulo de Compras de Productos\n\n" +
                "Permite al usuario agregar productos al carrito,\n" +
                "ver el total a pagar y finalizar la compra.",
                "Acerca de",
                JOptionPane.INFORMATION_MESSAGE
        );
    });

    menuAyuda.add(itemAcerca);

    // ───── Añadir todos los menús a la barra ─────
    barra.add(menuCarrito);
    barra.add(menuSesion);
    barra.add(menuAyuda);

    // ───── Asignar la barra al JFrame ─────
    setJMenuBar(barra);
}

    





    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new usuarioCompra2().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarCarrito;
    private javax.swing.JButton btnEliminarProducto;
    private javax.swing.JButton btnFinalizarCompra;
    private javax.swing.JButton btnVaciarCarrito;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPaneCarrito;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblTotalPagar;
    private javax.swing.JList<String> lstProductosUsuario;
    private javax.swing.JPanel panelDerecha;
    private javax.swing.JPanel panelIzquierda;
    private javax.swing.JTable tblCarrito;
    private javax.swing.JTextField txtBuscarUsuario;
    private javax.swing.JTextField txtCantidadComprar;
    // End of variables declaration//GEN-END:variables
}
