/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package capasPresentacion;

import Clases.Producto;
import Clasesdao.ProductoDAO;
import java.util.List;
import javax.swing.DefaultComboBoxModel;

/**
 *
 * @author LAS
 */

public class usuarioCompra extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(usuarioCompra.class.getName());

    /**
     * Creates new form usuarioCompra
     */
    public usuarioCompra() {
        initComponents();
         cargarProductos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
private List<Producto> listaProductos; // Agrega esta variable al inicio de la clase

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnEliminarProdcuto = new javax.swing.JButton();
        btnCompra = new javax.swing.JButton();
        cmbProducto = new javax.swing.JComboBox<>();
        btnAgregar = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        txtCantidad = new javax.swing.JTextField();
        jTextArea1 = new java.awt.TextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("Compra Productos");

        jLabel2.setText("Cantidad:");

        jLabel3.setText("Producto:");

        btnEliminarProdcuto.setText("Eliminar Producto");
        btnEliminarProdcuto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarProdcutoActionPerformed(evt);
            }
        });

        btnCompra.setText("Compra");
        btnCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCompraActionPerformed(evt);
            }
        });

        cmbProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbProductoActionPerformed(evt);
            }
        });

        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        txtCantidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCantidadActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(173, 173, 173)
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnCompra, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 387, Short.MAX_VALUE)
                    .addComponent(btnEliminarProdcuto, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cmbProducto, 0, 160, Short.MAX_VALUE)
                            .addComponent(txtCantidad))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAgregar))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jTextArea1, javax.swing.GroupLayout.PREFERRED_SIZE, 378, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(13, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(btnAgregar))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabel2)
                        .addGap(22, 22, 22))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextArea1, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEliminarProdcuto)
                .addGap(12, 12, 12)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCompra)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
private void cargarProductos() {
        ProductoDAO productoDAO = new ProductoDAO();
       listaProductos = productoDAO.listarTodos(); // Guardar la lista completa

        List<Producto> productos = productoDAO.listarTodos(); // Obtener lista de productos desde la base de datos
        
        // Crear un modelo para el comboBox
        DefaultComboBoxModel<String> modeloCombo = new DefaultComboBoxModel<>();
        
        // Llenar el comboBox con los nombres de los productos
        for (Producto producto : productos) {
            modeloCombo.addElement(producto.getNombre()); // Se agrega el nombre del producto
        }

        // Establecer el modelo al JComboBox
        cmbProducto.setModel(modeloCombo);
    }
    private void cmbProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbProductoActionPerformed
         
    }//GEN-LAST:event_cmbProductoActionPerformed

    private void txtCantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCantidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCantidadActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
         try {
        // Obtener el producto seleccionado y la cantidad
        String productoSeleccionado = cmbProducto.getSelectedItem().toString();
        String cantidadStr = txtCantidad.getText().trim();
        
        // Validar que se ingresó una cantidad
        if (cantidadStr.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Ingrese una cantidad", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        int cantidad;
        try {
            cantidad = Integer.parseInt(cantidadStr);
            if (cantidad <= 0) {
                javax.swing.JOptionPane.showMessageDialog(this, "La cantidad debe ser mayor a cero", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
                return;
            }
        } catch (NumberFormatException e) {
            javax.swing.JOptionPane.showMessageDialog(this, "La cantidad debe ser un número válido", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        // Buscar el producto completo en la lista para obtener el precio
        Producto productoCompleto = null;
        for (Producto p : listaProductos) {
            if (p.getNombre().equals(productoSeleccionado)) {
                productoCompleto = p;
                break;
            }
        }
        
        if (productoCompleto == null) {
            javax.swing.JOptionPane.showMessageDialog(this, "Producto no encontrado", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        // Calcular subtotal
        double precio = productoCompleto.getPrecioProducto().doubleValue();
        double subtotal = precio * cantidad;
        
        // Agregar al JTextArea con precio y subtotal
        String linea = String.format("%s - Cantidad: %d - Precio: $%.2f - Subtotal: $%.2f", 
                                    productoSeleccionado, cantidad, precio, subtotal);
        jTextArea1.append(linea + "\n");
        
        // Limpiar campo de cantidad
        txtCantidad.setText("");
        
    } catch (Exception e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Error al agregar producto: " + e.getMessage(), "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnEliminarProdcutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarProdcutoActionPerformed
        // TODO add your handling code here:
        // Verificar si hay texto seleccionado en el JTextArea
     try {
        // Obtener toda la línea donde está el cursor
        String textoCompleto = jTextArea1.getText();
        int posicionCursor = jTextArea1.getCaretPosition();
        
        // Dividir en líneas
        String[] lineas = textoCompleto.split("\n");
        int lineaActual = 0;
        int acumulado = 0;
        
        // Encontrar en qué línea está el cursor
        for (int i = 0; i < lineas.length; i++) {
            acumulado += lineas[i].length() + 1; // +1 por el \n
            if (posicionCursor < acumulado) {
                lineaActual = i;
                break;
            }
        }
        
        if (lineaActual >= lineas.length) {
            javax.swing.JOptionPane.showMessageDialog(this, "No hay producto para eliminar", "Advertencia", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        String lineaSeleccionada = lineas[lineaActual].trim();
        
        if (lineaSeleccionada.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Línea vacía", "Advertencia", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        // Mostrar diálogo de confirmación
        int confirmacion = javax.swing.JOptionPane.showConfirmDialog(this, 
            "¿Eliminar este producto?\n" + lineaSeleccionada, 
            "Confirmar Eliminación", 
            javax.swing.JOptionPane.YES_NO_OPTION);
        
        if (confirmacion == javax.swing.JOptionPane.YES_OPTION) {
            // Eliminar la línea
            StringBuilder nuevoTexto = new StringBuilder();
            for (int i = 0; i < lineas.length; i++) {
                if (i != lineaActual) {
                    nuevoTexto.append(lineas[i]).append("\n");
                }
            }
            jTextArea1.setText(nuevoTexto.toString().trim());
            javax.swing.JOptionPane.showMessageDialog(this, "Producto eliminado", "Éxito", javax.swing.JOptionPane.INFORMATION_MESSAGE);
        }
        
    } catch (Exception e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Error: " + e.getMessage(), "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_btnEliminarProdcutoActionPerformed

    private void btnCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCompraActionPerformed
        // TODO add your handling code here:
       String textoCompleto = jTextArea1.getText().trim();
    
    if (textoCompleto.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this, 
            "🛒 El carrito de compras está vacío", 
            "Carrito Vacío", 
            javax.swing.JOptionPane.WARNING_MESSAGE);
        return;
    }
    
    try {
        String[] lineas = textoCompleto.split("\n");
        StringBuilder detalle = new StringBuilder();
        detalle.append("🛒 DETALLE DE COMPRA 🛒\n");
        detalle.append("═══════════════════════\n\n");
        
        double totalCompra = 0.0;
        int totalItems = 0;
        
        for (int i = 0; i < lineas.length; i++) {
            String linea = lineas[i].trim();
            if (!linea.isEmpty()) {
                detalle.append("• ").append(linea).append("\n");
                totalItems++;
                
                // Extraer el subtotal directamente de la línea
                // Buscar "Subtotal: $X.XX" en la línea
                String[] partes = linea.split(" - ");
                for (String parte : partes) {
                    if (parte.trim().startsWith("Subtotal: $")) {
                        String subtotalStr = parte.replace("Subtotal: $", "").trim();
                        double subtotal = Double.parseDouble(subtotalStr);
                        totalCompra += subtotal;
                        break;
                    }
                }
            }
        }
        
        // Calcular impuestos
        double iva = totalCompra * 0.19;
        double totalFinal = totalCompra + iva;
        
        // Agregar resumen
        detalle.append("\n═══════════════════════\n");
        detalle.append("📊 RESUMEN DE COMPRA\n");
        detalle.append("═══════════════════════\n");
        detalle.append("• Productos en carrito: ").append(totalItems).append("\n");
        detalle.append("• Subtotal: $").append(String.format("%.2f", totalCompra)).append("\n");
        detalle.append("• IVA (19%): $").append(String.format("%.2f", iva)).append("\n");
        detalle.append("• TOTAL FINAL: $").append(String.format("%.2f", totalFinal)).append("\n");
        
        javax.swing.JOptionPane.showMessageDialog(this, 
            detalle.toString(), 
            "✅ Resumen de Compra", 
            javax.swing.JOptionPane.INFORMATION_MESSAGE);
            
    } catch (Exception e) {
        javax.swing.JOptionPane.showMessageDialog(this, 
            "Error al procesar la compra: " + e.getMessage(), 
            "Error", 
            javax.swing.JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_btnCompraActionPerformed
    
  
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new usuarioCompra().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnCompra;
    private javax.swing.JButton btnEliminarProdcuto;
    private javax.swing.JComboBox<String> cmbProducto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private java.awt.TextArea jTextArea1;
    private javax.swing.JTextField txtCantidad;
    // End of variables declaration//GEN-END:variables
}
