/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package SQL;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import SQL.Conexion;


/**
 *
 * @author LAS
 */
public class conexionSQL extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(conexionSQL.class.getName());

    /**
     * Creates new form conexionSQL
     */
    public conexionSQL() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(147, 147, 147)
                .addComponent(jButton1)
                .addContainerGap(178, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(118, 118, 118)
                .addComponent(jButton1)
                .addContainerGap(159, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // Inicializa la variable que contendrá los nombres de las bases de datos
    String bases = "";

    try {
        // Obtén la conexión
        Connection con = Conexion.getConexion();

        // Verifica si la conexión es nula
        if (con == null) {
            JOptionPane.showMessageDialog(null, "Error: No se pudo establecer la conexión.");
            return;  // Salir si no se pudo conectar
        }

        // Si la conexión es válida, crea el statement
        Statement sql = con.createStatement();

        // Consulta para obtener el nombre de la base de datos 'Tienda'
        String consulta = "SELECT name FROM sys.databases WHERE name = 'Tienda'";
        ResultSet resultado = sql.executeQuery(consulta);

        // Itera sobre los resultados y los concatena en la variable 'bases'
        while (resultado.next()) {
            bases += resultado.getString(1) + "\n";  // Debería devolver solo 'Tienda'
        }

        // Muestra los resultados en un JOptionPane
        if (!bases.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Base de datos encontrada: " + bases);
        } else {
            JOptionPane.showMessageDialog(null, "La base de datos 'Tienda' no existe.");
        }

        // Cierra los recursos
        resultado.close();
        sql.close();
        con.close();

    } catch (SQLException ex) {
        // Muestra el error si ocurre alguna excepción
        JOptionPane.showMessageDialog(null, "Error SQL: " + ex.toString());
    }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new conexionSQL().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    // End of variables declaration//GEN-END:variables
}
